import type { Fingerprint } from '../types.js';

/** Analytics, tag managers, session replay, experimentation and feature flags. */
export const analytics: Fingerprint[] = [
  {
    name: 'Google Analytics 4',
    categories: ['analytics'],
    website: 'https://marketingplatform.google.com/about/analytics/',
    scriptSrc: [{ re: 'googletagmanager\\.com/gtag/js\\?id=(G-[A-Z0-9]+)', id: '$1', caseSensitive: true }],
    html: [
      { re: '\\b(G-[A-Z0-9]{9,12})\\b', id: '$1', caseSensitive: true, note: 'GA4 measurement ID' },
    ],
    js: { gtag: '', dataLayer: '' },
    requestHost: ['(?:www\\.)?google-analytics\\.com', 'analytics\\.google\\.com'],
    implies: ['Google Tag Manager'],
  },
  {
    name: 'Universal Analytics',
    categories: ['analytics'],
    website: 'https://support.google.com/analytics/answer/10089681',
    scriptSrc: ['google-analytics\\.com/(?:analytics|ga)\\.js'],
    html: [{ re: '\\b(UA-\\d{4,10}-\\d{1,4})\\b', id: '$1', caseSensitive: true }],
  },
  {
    name: 'Google Tag Manager',
    categories: ['tag-manager'],
    website: 'https://tagmanager.google.com',
    scriptSrc: ['googletagmanager\\.com/gtm\\.js', 'googletagmanager\\.com/gtag/js'],
    html: [{ re: '\\b(GTM-[A-Z0-9]{6,10})\\b', id: '$1', caseSensitive: true, note: 'GTM container ID' }],
    js: { google_tag_manager: '', dataLayer: '' },
  },
  {
    name: 'Stape',
    categories: ['tag-manager'],
    website: 'https://stape.io',
    scriptSrc: ['stape\\.io', 'stapetag'],
    requestHost: ['\\.stape\\.io'],
    description: 'Server-side Google Tag Manager hosting',
    implies: ['Google Tag Manager'],
  },
  {
    name: 'Plausible Analytics',
    categories: ['analytics'],
    website: 'https://plausible.io',
    scriptSrc: ['plausible\\.io/js/', 'plausible(?:\\.outbound-links)?\\.js'],
    requestHost: ['plausible\\.io'],
  },
  {
    name: 'Fathom Analytics',
    categories: ['analytics'],
    website: 'https://usefathom.com',
    scriptSrc: ['cdn\\.usefathom\\.com'],
    js: { fathom: '' },
  },
  {
    name: 'Umami',
    categories: ['analytics'],
    website: 'https://umami.is',
    scriptSrc: ['umami.*?/script\\.js', 'cloud\\.umami\\.is'],
    html: ['data-website-id'],
  },
  {
    name: 'Matomo',
    categories: ['analytics'],
    website: 'https://matomo.org',
    scriptSrc: ['matomo\\.js', 'piwik\\.js'],
    js: { _paq: '', Matomo: '' },
  },
  {
    name: 'PostHog',
    categories: ['product-analytics', 'feature-flags'],
    website: 'https://posthog.com',
    scriptSrc: ['posthog\\.com/static/array\\.js', 'posthog-js'],
    js: { posthog: '' },
    requestHost: ['(?:app|us|eu)\\.posthog\\.com', '\\.i\\.posthog\\.com'],
    npmDep: ['^posthog-js$'],
  },
  {
    name: 'Mixpanel',
    categories: ['product-analytics'],
    website: 'https://mixpanel.com',
    scriptSrc: ['cdn\\.mxpnl\\.com', 'cdn\\d?\\.mixpanel\\.com'],
    js: { mixpanel: '' },
    requestHost: ['api(?:-js)?\\.mixpanel\\.com'],
  },
  {
    name: 'Amplitude',
    categories: ['product-analytics'],
    website: 'https://amplitude.com',
    scriptSrc: ['cdn\\.amplitude\\.com', 'cdn\\.eu\\.amplitude\\.com'],
    js: { amplitude: '' },
    requestHost: ['api\\d?\\.amplitude\\.com'],
  },
  {
    name: 'Heap',
    categories: ['product-analytics'],
    website: 'https://www.heap.io',
    scriptSrc: ['cdn\\.heapanalytics\\.com', 'cdn\\d?\\.heap\\.io'],
    js: { heap: '' },
  },
  {
    name: 'Segment',
    categories: ['analytics', 'tag-manager'],
    website: 'https://segment.com',
    scriptSrc: ['cdn\\.segment\\.com/analytics\\.js'],
    js: { 'analytics.SNIPPET_VERSION': { re: '([\\d.]+)', version: '$1' } },
    requestHost: ['api\\.segment\\.io'],
  },
  {
    name: 'RudderStack',
    categories: ['analytics', 'tag-manager'],
    website: 'https://www.rudderstack.com',
    scriptSrc: ['rudderlabs\\.com', 'rudder-analytics'],
    js: { rudderanalytics: '' },
  },
  {
    name: 'Snowplow',
    categories: ['analytics'],
    website: 'https://snowplow.io',
    scriptSrc: [{ re: '@snowplow/javascript-tracker@([\\d.]+)', version: '$1' }, 'sp(?:\\.min)?\\.js'],
    js: { snowplow: '' },
    npmDep: ['^@snowplow/'],
  },
  {
    name: 'Microsoft Clarity',
    categories: ['analytics'],
    website: 'https://clarity.microsoft.com',
    scriptSrc: [{ re: 'clarity\\.ms/tag/([a-z0-9]+)', id: '$1' }],
    js: { clarity: '' },
    requestHost: ['\\.clarity\\.ms'],
  },
  {
    name: 'Hotjar',
    categories: ['analytics'],
    website: 'https://www.hotjar.com',
    scriptSrc: ['static\\.hotjar\\.com', 'script\\.hotjar\\.com'],
    js: { hj: '', _hjSettings: '' },
  },
  {
    name: 'FullStory',
    categories: ['analytics'],
    website: 'https://www.fullstory.com',
    scriptSrc: ['fullstory\\.com/s/fs\\.js', 'edge\\.fullstory\\.com'],
    js: { FS: '', _fs_namespace: '' },
  },
  {
    name: 'LogRocket',
    categories: ['analytics', 'error-tracking'],
    website: 'https://logrocket.com',
    scriptSrc: ['cdn\\.log(?:rocket|r)\\.io', 'cdn\\.lr-'],
    js: { LogRocket: '' },
    npmDep: ['^logrocket$'],
  },
  {
    name: 'Smartlook',
    categories: ['analytics'],
    website: 'https://www.smartlook.com',
    scriptSrc: ['web-sdk\\.smartlook\\.com', 'rec\\.smartlook\\.com'],
    js: { smartlook: '' },
  },
  {
    name: 'Vercel Analytics',
    categories: ['analytics'],
    website: 'https://vercel.com/analytics',
    scriptSrc: ['/_vercel/insights/script\\.js', '/_vercel/speed-insights/script\\.js'],
    npmDep: ['^@vercel/analytics$', '^@vercel/speed-insights$'],
  },
  {
    name: 'Cloudflare Web Analytics',
    categories: ['analytics'],
    website: 'https://www.cloudflare.com/web-analytics/',
    scriptSrc: ['static\\.cloudflareinsights\\.com/beacon'],
  },
  {
    name: 'Adobe Analytics',
    categories: ['analytics'],
    website: 'https://business.adobe.com/products/analytics/adobe-analytics.html',
    scriptSrc: ['AppMeasurement\\.js', 'assets\\.adobedtm\\.com'],
    js: { s_c_il: '', 'AppMeasurement': '' },
  },
  {
    name: 'Pirsch',
    categories: ['analytics'],
    website: 'https://pirsch.io',
    scriptSrc: ['api\\.pirsch\\.io/pirsch'],
  },
  {
    name: 'GoatCounter',
    categories: ['analytics'],
    website: 'https://www.goatcounter.com',
    scriptSrc: ['gc\\.zgo\\.at/count\\.js'],
  },
  {
    name: 'Simple Analytics',
    categories: ['analytics'],
    website: 'https://www.simpleanalytics.com',
    scriptSrc: ['scripts\\.simpleanalyticscdn\\.com'],
  },
  {
    name: 'Optimizely',
    categories: ['ab-testing'],
    website: 'https://www.optimizely.com',
    scriptSrc: ['cdn\\.optimizely\\.com'],
    js: { optimizely: '' },
  },
  {
    name: 'VWO',
    categories: ['ab-testing'],
    website: 'https://vwo.com',
    scriptSrc: ['dev\\.visualwebsiteoptimizer\\.com'],
    js: { _vwo_code: '', VWO: '' },
  },
  {
    name: 'AB Tasty',
    categories: ['ab-testing'],
    website: 'https://www.abtasty.com',
    scriptSrc: ['try\\.abtasty\\.com'],
    js: { ABTasty: '' },
  },
  {
    name: 'Kameleoon',
    categories: ['ab-testing'],
    website: 'https://www.kameleoon.com',
    scriptSrc: ['kameleoon\\.(?:io|eu|com)'],
    js: { Kameleoon: '' },
  },
  {
    name: 'Convert',
    categories: ['ab-testing'],
    website: 'https://www.convert.com',
    scriptSrc: ['cdn-\\d+\\.convertexperiments\\.com'],
  },
  {
    name: 'LaunchDarkly',
    categories: ['feature-flags'],
    website: 'https://launchdarkly.com',
    requestHost: ['\\.launchdarkly\\.com'],
    npmDep: ['^launchdarkly-'],
  },
  {
    name: 'Statsig',
    categories: ['feature-flags', 'ab-testing'],
    website: 'https://www.statsig.com',
    requestHost: ['\\.statsig\\.com'],
    npmDep: ['^statsig-', '^@statsig/'],
  },
  {
    name: 'GrowthBook',
    categories: ['feature-flags', 'ab-testing'],
    website: 'https://www.growthbook.io',
    requestHost: ['cdn\\.growthbook\\.io'],
    npmDep: ['^@growthbook/'],
  },
  {
    name: 'Split',
    categories: ['feature-flags'],
    website: 'https://www.split.io',
    requestHost: ['\\.split\\.io'],
  },
];

/** Advertising pixels and conversion tracking. */
export const advertising: Fingerprint[] = [
  {
    name: 'Meta Pixel',
    categories: ['advertising'],
    website: 'https://www.facebook.com/business/tools/meta-pixel',
    scriptSrc: ['connect\\.facebook\\.net/[^/]+/fbevents\\.js'],
    js: { fbq: '' },
    html: [{ re: "fbq\\('init',\\s*'(\\d{13,17})'", id: '$1' }],
    requestHost: ['(?:www|connect)\\.facebook\\.(?:net|com)'],
  },
  {
    name: 'Google Ads',
    categories: ['advertising'],
    website: 'https://ads.google.com',
    scriptSrc: [{ re: 'googletagmanager\\.com/gtag/js\\?id=(AW-\\d+)', id: '$1', caseSensitive: true }],
    html: [{ re: '\\b(AW-\\d{9,12})\\b', id: '$1', caseSensitive: true }],
    requestHost: ['googleadservices\\.com', 'googlesyndication\\.com'],
  },
  {
    name: 'Google Ads Remarketing',
    categories: ['advertising'],
    website: 'https://ads.google.com',
    scriptSrc: ['googleads\\.g\\.doubleclick\\.net', 'www\\.googleadservices\\.com/pagead/conversion'],
  },
  {
    name: 'TikTok Pixel',
    categories: ['advertising'],
    website: 'https://ads.tiktok.com',
    scriptSrc: ['analytics\\.tiktok\\.com'],
    js: { ttq: '' },
  },
  {
    name: 'Pinterest Tag',
    categories: ['advertising'],
    website: 'https://ads.pinterest.com',
    scriptSrc: ['s\\.pinimg\\.com/ct/core\\.js'],
    js: { pintrk: '' },
    html: [{ re: "pintrk\\('load',\\s*'(\\d+)'", id: '$1' }],
  },
  {
    name: 'LinkedIn Insight Tag',
    categories: ['advertising'],
    website: 'https://www.linkedin.com/campaignmanager/',
    scriptSrc: ['snap\\.licdn\\.com/li\\.lms-analytics'],
    js: { _linkedin_partner_id: '' },
  },
  {
    name: 'X Pixel',
    categories: ['advertising'],
    website: 'https://ads.x.com',
    scriptSrc: ['static\\.ads-twitter\\.com/uwt\\.js'],
    js: { twq: '' },
  },
  {
    name: 'Snapchat Pixel',
    categories: ['advertising'],
    website: 'https://ads.snapchat.com',
    scriptSrc: ['sc-static\\.net/scevent\\.min\\.js'],
    js: { snaptr: '' },
  },
  {
    name: 'Reddit Pixel',
    categories: ['advertising'],
    website: 'https://ads.reddit.com',
    scriptSrc: ['(?:www\\.)?redditstatic\\.com/ads/pixel\\.js'],
    js: { rdt: '' },
  },
  {
    name: 'Microsoft Advertising',
    categories: ['advertising'],
    website: 'https://ads.microsoft.com',
    scriptSrc: ['bat\\.bing\\.com/bat\\.js', 'bat\\.bing\\.net'],
    js: { uetq: '' },
  },
  {
    name: 'Criteo',
    categories: ['advertising'],
    website: 'https://www.criteo.com',
    scriptSrc: ['static\\.criteo\\.net'],
  },
  {
    name: 'Taboola',
    categories: ['advertising'],
    website: 'https://www.taboola.com',
    scriptSrc: ['cdn\\.taboola\\.com'],
    js: { _taboola: '' },
  },
  {
    name: 'Outbrain',
    categories: ['advertising'],
    website: 'https://www.outbrain.com',
    scriptSrc: ['widgets\\.outbrain\\.com', 'amplify\\.outbrain\\.com'],
  },
  {
    name: 'AdRoll',
    categories: ['advertising'],
    website: 'https://www.adroll.com',
    scriptSrc: ['s\\.adroll\\.com', 'd\\.adroll\\.com'],
    js: { __adroll: '' },
  },
  {
    name: 'Google AdSense',
    categories: ['advertising'],
    website: 'https://adsense.google.com',
    scriptSrc: ['pagead2\\.googlesyndication\\.com/pagead/js/adsbygoogle\\.js'],
    js: { adsbygoogle: '' },
  },
];
