import type { Fingerprint } from '../types.js';

/** Payment processors and checkout providers. */
export const payments: Fingerprint[] = [
  {
    name: 'Stripe',
    categories: ['payment'],
    website: 'https://stripe.com',
    scriptSrc: ['js\\.stripe\\.com'],
    js: { Stripe: '' },
    requestHost: ['js\\.stripe\\.com', 'api\\.stripe\\.com', 'm\\.stripe\\.(?:com|network)'],
    npmDep: ['^@stripe/'],
  },
  {
    name: 'PayPal',
    categories: ['payment'],
    website: 'https://www.paypal.com',
    scriptSrc: ['www\\.paypal(?:objects)?\\.com/(?:sdk|api)'],
    js: { paypal: '' },
    requestHost: ['\\.paypal\\.com', 'paypalobjects\\.com'],
  },
  {
    name: 'Braintree',
    categories: ['payment'],
    website: 'https://www.braintreepayments.com',
    scriptSrc: ['js\\.braintreegateway\\.com'],
    js: { braintree: '' },
  },
  {
    name: 'Adyen',
    categories: ['payment'],
    website: 'https://www.adyen.com',
    scriptSrc: ['checkoutshopper-(?:live|test)\\.adyen\\.com'],
    js: { AdyenCheckout: '' },
  },
  {
    name: 'Checkout.com',
    categories: ['payment'],
    website: 'https://www.checkout.com',
    scriptSrc: ['cdn\\.checkout\\.com', 'js\\.checkout\\.com'],
  },
  {
    name: 'Square',
    categories: ['payment'],
    website: 'https://squareup.com',
    scriptSrc: ['(?:web|js)\\.squarecdn\\.com', 'js\\.squareup\\.com'],
  },
  {
    name: 'Razorpay',
    categories: ['payment'],
    website: 'https://razorpay.com',
    scriptSrc: ['checkout\\.razorpay\\.com'],
    js: { Razorpay: '' },
  },
  {
    name: 'GoKwik',
    categories: ['payment'],
    website: 'https://www.gokwik.co',
    scriptSrc: ['(?:pdp|sdk|api)\\.gokwik\\.co'],
    requestHost: ['\\.gokwik\\.co'],
    js: { gokwikSdk: '' },
    description: 'Kwik Checkout, one-click checkout for Indian ecommerce',
  },
  {
    name: 'KwikPass',
    categories: ['auth'],
    website: 'https://www.gokwik.co/kwikpass',
    scriptSrc: ['gokwik\\.co/kwikpass'],
    description: 'OTP based single sign-on from GoKwik',
    implies: ['GoKwik'],
  },
  {
    name: 'Cashfree',
    categories: ['payment'],
    website: 'https://www.cashfree.com',
    scriptSrc: ['sdk\\.cashfree\\.com'],
  },
  {
    name: 'PhonePe',
    categories: ['payment'],
    website: 'https://www.phonepe.com',
    scriptSrc: ['mercury\\.phonepe\\.com'],
  },
  {
    name: 'Paytm',
    categories: ['payment'],
    website: 'https://paytm.com',
    scriptSrc: ['secure\\.paytm(?:gateway)?\\.in'],
  },
  {
    name: 'Klarna',
    categories: ['payment'],
    website: 'https://www.klarna.com',
    scriptSrc: ['(?:x|js|eu-library)\\.klarnacdn\\.net', 'klarna(?:services)?\\.com'],
    js: { Klarna: '' },
  },
  {
    name: 'Afterpay',
    categories: ['payment'],
    website: 'https://www.afterpay.com',
    scriptSrc: ['static\\.afterpay\\.com', 'js\\.afterpay\\.com'],
  },
  {
    name: 'Affirm',
    categories: ['payment'],
    website: 'https://www.affirm.com',
    scriptSrc: ['cdn\\d?\\.affirm\\.com'],
    js: { affirm: '' },
  },
  {
    name: 'Paddle',
    categories: ['payment', 'subscription'],
    website: 'https://www.paddle.com',
    scriptSrc: ['cdn\\.paddle\\.com'],
    js: { Paddle: '' },
  },
  {
    name: 'Lemon Squeezy',
    categories: ['payment', 'subscription'],
    website: 'https://www.lemonsqueezy.com',
    scriptSrc: ['assets\\.lemonsqueezy\\.com'],
    requestHost: ['\\.lemonsqueezy\\.com'],
  },
  {
    name: 'Polar',
    categories: ['payment', 'subscription'],
    website: 'https://polar.sh',
    requestHost: ['(?:api\\.)?polar\\.sh'],
    npmDep: ['^@polar-sh/'],
  },
  {
    name: 'Chargebee',
    categories: ['subscription'],
    website: 'https://www.chargebee.com',
    scriptSrc: ['js\\.chargebee\\.com'],
    js: { Chargebee: '' },
  },
  {
    name: 'Recurly',
    categories: ['subscription'],
    website: 'https://recurly.com',
    scriptSrc: ['js\\.recurly\\.com'],
    js: { recurly: '' },
  },
  {
    name: 'Mollie',
    categories: ['payment'],
    website: 'https://www.mollie.com',
    scriptSrc: ['js\\.mollie\\.com'],
  },
  {
    name: 'Shop Pay',
    categories: ['payment'],
    website: 'https://shop.app',
    scriptSrc: ['shop\\.app/checkouts', 'shopifycloud/(?:shop-js|storefront/assets/shopify_pay)'],
    requires: ['Shopify'],
  },
];

/**
 * Ecommerce applications, heavily weighted towards the Shopify app ecosystem.
 *
 * Shopify app blocks are served from `cdn.shopify.com/extensions/<uuid>/<handle>-<n>/`,
 * where the handle names the app directly. That path is the single most reliable way to
 * enumerate a Shopify store's installed apps, and it is why this database matches on it.
 */
export const commerceApps: Fingerprint[] = [
  {
    name: 'Judge.me',
    categories: ['reviews', 'ecommerce-app'],
    website: 'https://judge.me',
    scriptSrc: ['cdn\\d?\\.judge\\.me', 'extensions/[^/]+/judgeme-'],
    requestHost: ['(?:app|api|cdn\\d?|cdnwidget)\\.judge\\.me'],
  },
  {
    name: 'Yotpo',
    categories: ['reviews', 'loyalty', 'ecommerce-app'],
    website: 'https://www.yotpo.com',
    scriptSrc: ['(?:staticw2|cdn-widgetsrepository)\\.yotpo\\.com'],
    js: { yotpo: '' },
  },
  {
    name: 'Okendo',
    categories: ['reviews', 'ecommerce-app'],
    website: 'https://www.okendo.io',
    scriptSrc: ['d3hw6dc1ow8pp2\\.cloudfront\\.net', 'okendo\\.io'],
  },
  {
    name: 'Loox',
    categories: ['reviews', 'ecommerce-app'],
    website: 'https://loox.io',
    scriptSrc: ['loox\\.io/widget'],
  },
  {
    name: 'Stamped.io',
    categories: ['reviews', 'ecommerce-app'],
    website: 'https://stamped.io',
    scriptSrc: ['cdn\\d?\\.stamped\\.io'],
  },
  {
    name: 'Trustpilot',
    categories: ['reviews'],
    website: 'https://www.trustpilot.com',
    scriptSrc: ['widget\\.trustpilot\\.com', 'invitejs\\.trustpilot\\.com'],
  },
  {
    name: 'Reviews.io',
    categories: ['reviews'],
    website: 'https://www.reviews.io',
    scriptSrc: ['widget\\.reviews\\.(?:io|co\\.uk)'],
  },
  {
    name: 'Fera',
    categories: ['reviews', 'ecommerce-app'],
    website: 'https://www.fera.ai',
    scriptSrc: ['cdn\\.fera\\.ai'],
  },
  {
    name: 'Rebuy',
    categories: ['personalisation', 'ecommerce-app'],
    website: 'https://rebuyengine\\.com',
    scriptSrc: ['cdn\\.rebuyengine\\.com'],
  },
  {
    name: 'Recharge',
    categories: ['subscription', 'ecommerce-app'],
    website: 'https://rechargepayments.com',
    scriptSrc: ['static\\.rechargecdn\\.com', 'rechargeapps\\.com'],
  },
  {
    name: 'Skio',
    categories: ['subscription', 'ecommerce-app'],
    website: 'https://skio.com',
    scriptSrc: ['cdn\\.skio\\.com'],
  },
  {
    name: 'Loop Subscriptions',
    categories: ['subscription', 'ecommerce-app'],
    website: 'https://www.loopwork.co',
    scriptSrc: ['cdn\\.loopwork\\.co', 'loop-subscription'],
  },
  {
    name: 'Smile.io',
    categories: ['loyalty', 'ecommerce-app'],
    website: 'https://smile.io',
    scriptSrc: ['cdn\\.smile\\.io'],
  },
  {
    name: 'LoyaltyLion',
    categories: ['loyalty', 'ecommerce-app'],
    website: 'https://loyaltylion.com',
    scriptSrc: ['sdk\\.loyaltylion\\.(?:com|net)'],
  },
  {
    name: 'Nector',
    categories: ['loyalty', 'ecommerce-app'],
    website: 'https://nector.io',
    scriptSrc: ['(?:cdn|platform|websdk)\\.nector\\.io'],
  },
  {
    name: 'Flits',
    categories: ['ecommerce-app'],
    website: 'https://getflits.com',
    scriptSrc: ['cdn\\.getflits\\.com', 'extensions/[^/]+/flits-'],
    description: 'Customer account page and store credit for Shopify',
  },
  {
    name: 'Gorgias',
    categories: ['support', 'ecommerce-app'],
    website: 'https://www.gorgias.com',
    scriptSrc: ['config\\.gorgias\\.chat', 'assets\\.gorgias\\.chat'],
  },
  {
    name: 'Shiprocket',
    categories: ['shipping', 'ecommerce-app'],
    website: 'https://www.shiprocket.in',
    scriptSrc: ['sr-cdn\\.shiprocket\\.in'],
    requestHost: ['\\.shiprocket\\.in'],
  },
  {
    name: 'AfterShip',
    categories: ['shipping', 'ecommerce-app'],
    website: 'https://www.aftership.com',
    scriptSrc: ['aftership\\.com'],
    requestHost: ['\\.aftership\\.com'],
  },
  {
    name: 'ParcelPanel',
    categories: ['shipping', 'ecommerce-app'],
    website: 'https://www.parcelpanel.com',
    scriptSrc: ['parcelpanel\\.(?:com|org)'],
  },
  {
    name: 'Route',
    categories: ['shipping', 'ecommerce-app'],
    website: 'https://route.com',
    scriptSrc: ['cdn\\.routeapp\\.io'],
  },
  {
    name: 'BOGOS',
    categories: ['ecommerce-app'],
    website: 'https://bogos.io',
    scriptSrc: ['cdn\\.bogos\\.io', 'secomapp\\.', 'extensions/[^/]+/freegifts-'],
    requestHost: ['(?:api|collect|cdn)\\.bogos\\.io'],
    description: 'Free gift and BOGO promotions for Shopify, by Secomapp',
  },
  {
    name: 'Corner',
    categories: ['ecommerce-app'],
    website: 'https://www.corner.inc',
    scriptSrc: ['extensions/[^/]+/corner-', 'cornerWidget\\.js'],
    description: 'Cart drawer, upsells and related items for Shopify',
  },
  {
    name: 'Vitals',
    categories: ['ecommerce-app'],
    website: 'https://vitals.co',
    scriptSrc: ['appsolve\\.io', 'vitals\\.co'],
  },
  {
    name: 'Boost AI Search',
    categories: ['search', 'ecommerce-app'],
    website: 'https://boostcommerce.net',
    scriptSrc: ['cdn\\.boostcommerce\\.net', 'boostcommerce'],
  },
  {
    name: 'Searchanise',
    categories: ['search', 'ecommerce-app'],
    website: 'https://searchanise.io',
    scriptSrc: ['searchserverapi\\.com', 'searchanise'],
  },
  {
    name: 'Nosto',
    categories: ['personalisation', 'ecommerce-app'],
    website: 'https://www.nosto.com',
    scriptSrc: ['connect\\.nosto\\.com'],
  },
  {
    name: 'Dynamic Yield',
    categories: ['personalisation'],
    website: 'https://www.dynamicyield.com',
    scriptSrc: ['cdn(?:-eu)?\\.dynamicyield\\.com'],
  },
  {
    name: 'LimeSpot',
    categories: ['personalisation', 'ecommerce-app'],
    website: 'https://www.limespot.com',
    scriptSrc: ['cdn\\.limespot\\.com'],
  },
  {
    name: 'GoAffPro',
    categories: ['ecommerce-app'],
    website: 'https://goaffpro.com',
    scriptSrc: ['goaffpro\\.com', 'widgets\\.goaffpro\\.app'],
    description: 'Affiliate and influencer program for Shopify',
  },
  {
    name: 'Retrics',
    categories: ['ecommerce-app'],
    website: 'https://retrics.ai',
    scriptSrc: ['geo\\.retrics\\.ai', 'extensions/[^/]+/retrics-redirect-'],
    description: 'Geolocation based storefront redirect',
  },
  {
    name: 'Verifast AI',
    categories: ['chat', 'ai', 'ecommerce-app'],
    website: 'https://verifast.ai',
    scriptSrc: ['(?:bot\\d*|static|p-ws-async)\\.verifast\\.ai', 'extensions/[^/]+/verifast-'],
  },
  {
    name: 'BiteSpeed',
    categories: ['marketing-automation', 'ecommerce-app'],
    website: 'https://bitespeed.co',
    scriptSrc: ['bitespeed', 'extensions/[^/]+/bitespeed-'],
    description: 'WhatsApp marketing and popups for Shopify',
  },
  {
    name: 'Wishlink',
    categories: ['ecommerce-app'],
    website: 'https://www.wishlink.com',
    requestHost: ['api\\.wishlink\\.com'],
  },
  {
    name: 'Zapiet',
    categories: ['ecommerce-app'],
    website: 'https://www.zapiet.com',
    scriptSrc: ['cdn\\.zapiet\\.com'],
  },
];

/** Popups, on-site conversion and consent tooling. */
export const conversion: Fingerprint[] = [
  {
    name: 'OptinMonster',
    categories: ['marketing-automation'],
    website: 'https://optinmonster.com',
    scriptSrc: ['a\\.omappapi\\.com', 'optinmonster\\.com'],
    js: { om_loaded: '' },
  },
  {
    name: 'Personizely',
    categories: ['marketing-automation', 'personalisation'],
    website: 'https://www.personizely.net',
    scriptSrc: ['static\\.personizely\\.net'],
  },
  {
    name: 'Privy',
    categories: ['marketing-automation'],
    website: 'https://www.privy.com',
    scriptSrc: ['widget\\.privy\\.com'],
  },
  {
    name: 'Justuno',
    categories: ['marketing-automation'],
    website: 'https://www.justuno.com',
    scriptSrc: ['cdn\\.justuno\\.com'],
  },
  {
    name: 'Wisepops',
    categories: ['marketing-automation'],
    website: 'https://wisepops.com',
    scriptSrc: ['loader\\.wisepops\\.com'],
  },
  {
    name: 'Sleeknote',
    categories: ['marketing-automation'],
    website: 'https://sleeknote.com',
    scriptSrc: ['sleeknotecustomerscripts\\.sleeknote\\.com'],
  },
  {
    name: 'OneTrust',
    categories: ['cookie-consent'],
    website: 'https://www.onetrust.com',
    scriptSrc: ['cdn\\.cookielaw\\.org', 'optanon'],
    js: { OneTrust: '', Optanon: '' },
  },
  {
    name: 'Cookiebot',
    categories: ['cookie-consent'],
    website: 'https://www.cookiebot.com',
    scriptSrc: ['consent\\.cookiebot\\.com'],
    js: { Cookiebot: '' },
  },
  {
    name: 'Usercentrics',
    categories: ['cookie-consent'],
    website: 'https://usercentrics.com',
    scriptSrc: ['app\\.usercentrics\\.eu', 'privacy-proxy\\.usercentrics\\.eu'],
  },
  {
    name: 'CookieYes',
    categories: ['cookie-consent'],
    website: 'https://www.cookieyes.com',
    scriptSrc: ['cdn-cookieyes\\.com'],
  },
  {
    name: 'Iubenda',
    categories: ['cookie-consent'],
    website: 'https://www.iubenda.com',
    scriptSrc: ['cdn\\.iubenda\\.com'],
  },
  {
    name: 'Osano',
    categories: ['cookie-consent'],
    website: 'https://www.osano.com',
    scriptSrc: ['cmp\\.osano\\.com'],
  },
  {
    name: 'Termly',
    categories: ['cookie-consent'],
    website: 'https://termly.io',
    scriptSrc: ['app\\.termly\\.io'],
  },
  {
    name: 'Didomi',
    categories: ['cookie-consent'],
    website: 'https://www.didomi.io',
    scriptSrc: ['sdk\\.privacy-center\\.org', 'didomi\\.io'],
    js: { Didomi: '' },
  },
];
