import type { Fingerprint } from '../types.js';

/**
 * Global ecommerce platforms and the wider merchant stack.
 *
 * Every pattern here is a hostname or an asset path, never a bare brand name in HTML. A
 * substring like "shopline" or "ecwid" matches any page that merely mentions the product,
 * including competitor comparison pages and the vendor's own blog. A request to
 * `vtexassets.com`, by contrast, cannot happen unless the site actually runs on VTEX.
 *
 * Handles under `cdn.shopify.com/extensions/<uuid>/<handle>-<n>/` were harvested from live
 * storefronts rather than guessed; the handle is assigned by Shopify and names the app.
 */

/** Ecommerce platforms outside the Shopify/Woo/Magento core already covered elsewhere. */
export const globalPlatforms: Fingerprint[] = [
  {
    name: 'VTEX',
    categories: ['ecommerce', 'platform'],
    website: 'https://vtex.com',
    description: 'Enterprise commerce platform, dominant across Latin America',
    // Verified on decathlon.com.br and motorola.com.br.
    html: ['vtexassets\\.com', '__RUNTIME__', 'vtexcommercestable\\.com\\.br'],
    requestHost: ['\\.vtexassets\\.com', '\\.vtexcommercestable\\.com\\.br', '\\.myvtex\\.com'],
    headers: { 'x-vtex-io-cluster-id': '', 'x-vtex-router-cache': '' },
  },
  {
    name: 'commercetools',
    categories: ['ecommerce', 'platform'],
    website: 'https://commercetools.com',
    description: 'Headless, API-first commerce',
    requestHost: ['api\\.[a-z-]+\\.commercetools\\.com', '\\.commercetools\\.com'],
    npmDep: ['^@commercetools/'],
  },
  {
    name: 'SAP Commerce Cloud',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.sap.com/products/commerce-cloud.html',
    description: 'Formerly Hybris',
    html: ['/_ui/responsive/', '/medias/sys_master/'],
    url: ['/[a-z]{2}/[a-z]{2}/c/|\\.html\\?q='],
    implies: ['Java'],
  },
  {
    name: 'Elastic Path',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.elasticpath.com',
    requestHost: ['\\.elasticpath\\.com', 'api\\.moltin\\.com'],
  },
  {
    name: 'Spryker',
    categories: ['ecommerce', 'platform'],
    website: 'https://spryker.com',
    html: ['/assets/current/Yves/', 'spryker'],
    headers: { 'x-spryker-': '' },
    implies: ['PHP'],
  },
  {
    name: 'Medusa',
    categories: ['ecommerce', 'platform'],
    website: 'https://medusajs.com',
    npmDep: ['^@medusajs/'],
    probe: [{ path: '/store/regions', body: '"regions"\\s*:' }],
    implies: ['Node.js'],
  },
  {
    name: 'Saleor',
    categories: ['ecommerce', 'platform'],
    website: 'https://saleor.io',
    requestHost: ['\\.saleor\\.cloud'],
    npmDep: ['^@saleor/'],
    implies: ['Python', 'GraphQL'],
  },
  {
    name: 'Swell',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.swell.is',
    requestHost: ['\\.swell\\.store', 'api\\.swell\\.is'],
    npmDep: ['^swell-js$'],
  },
  {
    name: 'Vendure',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.vendure.io',
    npmDep: ['^@vendure/'],
    implies: ['Node.js', 'GraphQL'],
  },
  {
    name: 'Ecwid',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.ecwid.com',
    // Host-based only: the word "ecwid" appears on countless pages that do not run it.
    requestHost: ['app\\.ecwid\\.com', 'd2j6dbq0eux0bg\\.cloudfront\\.net'],
    scriptSrc: ['app\\.ecwid\\.com/script\\.js'],
    js: { Ecwid: '' },
  },
  {
    name: 'Tiendanube',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.tiendanube.com',
    description: 'Nuvemshop, the leading platform for small merchants in Latin America',
    requestHost: ['\\.tiendanube\\.com', '\\.nuvemshop\\.com\\.br', 'd2r9epyceweg5n\\.cloudfront\\.net'],
    html: ['cdn\\.tiendanube\\.com', 'nuvemshop\\.com\\.br'],
  },
  {
    name: 'SHOPLINE',
    categories: ['ecommerce', 'platform'],
    website: 'https://shopline.com',
    description: 'Major platform across Greater China and Southeast Asia',
    requestHost: ['\\.shoplineapp\\.com', '\\.myshopline\\.com'],
    html: ['shoplineapp\\.com', 'shoplineimg\\.com'],
  },
  {
    name: 'Big Cartel',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.bigcartel.com',
    requestHost: ['assets\\.bigcartel\\.com', '\\.bigcartel\\.com'],
    html: ['assets\\.bigcartel\\.com'],
  },
  {
    name: 'Squarespace Commerce',
    categories: ['ecommerce'],
    website: 'https://www.squarespace.com/ecommerce-website',
    html: ['sqs-add-to-cart-button', 'commerce-product'],
    requires: ['Squarespace'],
    implies: ['Squarespace'],
  },
  {
    name: 'Wix Stores',
    categories: ['ecommerce'],
    website: 'https://www.wix.com/ecommerce/website',
    html: ['wixstores', 'stores\\.wix\\.com'],
    requires: ['Wix'],
    implies: ['Wix'],
  },
  {
    name: 'Webflow Ecommerce',
    categories: ['ecommerce'],
    website: 'https://webflow.com/ecommerce',
    html: ['data-wf-item-id', 'w-commerce-commerce'],
    requires: ['Webflow'],
    implies: ['Webflow'],
  },
  {
    name: 'Lightspeed eCom',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.lightspeedhq.com',
    requestHost: ['cdn\\.shoplightspeed\\.com', '\\.webshopapp\\.com'],
  },
  {
    name: 'Shift4Shop',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.shift4shop.com',
    requestHost: ['\\.shift4shop\\.com', '\\.3dcartstores\\.com'],
  },
  {
    name: 'Volusion',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.volusion.com',
    requestHost: ['\\.volusion\\.com'],
    html: ['/v/vspfiles/'],
  },
  {
    name: 'OpenCart',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.opencart.com',
    html: ['catalog/view/(?:theme|javascript)/', 'index\\.php\\?route=common/home'],
    cookies: { '^OCSESSID$': '' },
    implies: ['PHP'],
  },
  {
    name: 'nopCommerce',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.nopcommerce.com',
    html: ['/Themes/[A-Za-z]+/Content/', 'nopCommerce'],
    cookies: { '^Nop\\.customer$': '' },
    implies: ['ASP.NET'],
  },
  {
    name: 'CS-Cart',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.cs-cart.com',
    html: ['/var/cache/misc/assets/design/themes/', 'cm-ajax'],
    cookies: { '^cscart_': '' },
    implies: ['PHP'],
  },
  {
    name: 'Jumpseller',
    categories: ['ecommerce', 'platform'],
    website: 'https://jumpseller.com',
    requestHost: ['\\.jumpseller\\.com'],
  },
  {
    name: 'Dukaan',
    categories: ['ecommerce', 'platform'],
    website: 'https://mydukaan.io',
    description: 'India-focused SMB commerce platform',
    requestHost: ['\\.mydukaan\\.io', 'dukaan\\.b-cdn\\.net'],
  },
  {
    name: 'StoreHippo',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.storehippo.com',
    requestHost: ['\\.storehippo\\.com'],
  },
  {
    name: 'Shopify Hydrogen',
    categories: ['ecommerce', 'js-framework'],
    website: 'https://hydrogen.shopify.dev',
    description: 'Shopify headless storefront framework',
    npmDep: ['^@shopify/hydrogen'],
    html: ['__hydrogen', 'hydrogen-'],
    headers: { 'powered-by': 'Shopify Hydrogen' },
    implies: ['Remix', 'React'],
  },
  {
    name: 'Shopify Oxygen',
    categories: ['hosting'],
    website: 'https://shopify.dev/docs/custom-storefronts/oxygen',
    headers: { 'oxygen-full-page-cache': '', 'x-oxygen-': '' },
    implies: ['Shopify Hydrogen'],
  },
  {
    name: 'Vue Storefront',
    categories: ['ecommerce', 'js-framework'],
    website: 'https://vuestorefront.io',
    npmDep: ['^@vue-storefront/'],
    implies: ['Vue.js'],
  },
  {
    name: 'Shogun',
    categories: ['ecommerce-app'],
    website: 'https://getshogun.com',
    requestHost: ['\\.getshogun\\.com', 'i\\.shgcdn\\.com'],
    html: ['shg-c-|shogun-'],
  },
];

/**
 * Shopify apps, keyed on the app-block handle Shopify assigns.
 *
 * Handles were collected from live storefronts. The trailing number is the app's numeric id
 * and changes between installs, so it is matched loosely with `-\d+`.
 */
export const shopifyApps: Fingerprint[] = [
  {
    name: 'PushOwl',
    categories: ['marketing-automation', 'ecommerce-app'],
    website: 'https://pushowl.com',
    description: 'Web push notifications for Shopify',
    scriptSrc: ['extensions/[^/]+/pushowl-\\d+/', 'cdn\\.pushowl\\.com'],
    requestHost: ['\\.pushowl\\.com'],
  },
  {
    name: 'Swym',
    categories: ['ecommerce-app'],
    website: 'https://swymrelay.com',
    description: 'Wishlist, back-in-stock and price-drop alerts',
    scriptSrc: ['extensions/[^/]+/swym-relay-\\d+/', 'swymrelay\\.com'],
    requestHost: ['\\.swymrelay\\.com'],
  },
  {
    name: 'Redo',
    categories: ['shipping', 'ecommerce-app'],
    website: 'https://getredo.com',
    description: 'Returns coverage and package protection',
    scriptSrc: ['extensions/[^/]+/redo-v?[\\d.]+/', 'cdn\\.getredo\\.com'],
    requestHost: ['\\.getredo\\.com'],
  },
  {
    name: 'Rivo',
    categories: ['loyalty', 'ecommerce-app'],
    website: 'https://www.rivo.io',
    description: 'Loyalty and rewards for Shopify',
    // Merchants get a loyalty.rivo.io subdomain, seen live on drsquatch.com.
    requestHost: ['\\.rivo\\.io'],
    html: ['loyalty\\.rivo\\.io', 'rivo-loyalty'],
  },
  {
    name: 'Videowise',
    categories: ['video', 'ecommerce-app'],
    website: 'https://www.videowise.com',
    description: 'Shoppable video and UGC',
    requestHost: ['\\.videowise\\.com'],
    scriptSrc: ['(?:cdn\\d?|assets)\\.videowise\\.com'],
  },
  {
    name: 'Superfiliate',
    categories: ['ecommerce-app'],
    website: 'https://www.superfiliate.com',
    description: 'Creator affiliate and referral programme',
    requestHost: ['superfiliate-cdn\\.com', '\\.superfiliate\\.com'],
  },
  {
    name: 'Loop Returns',
    categories: ['shipping', 'ecommerce-app'],
    website: 'https://www.loopreturns.com',
    // Merchants get a <brand>.loopreturns.com subdomain, seen live on gymshark.com.
    requestHost: ['\\.loopreturns\\.com'],
    html: ['loopreturns\\.com'],
  },
  {
    name: 'SearchTap',
    categories: ['search', 'ecommerce-app'],
    website: 'https://www.searchtap.io',
    scriptSrc: ['extensions/[^/]+/searchtap-[a-z-]*\\d+/'],
    requestHost: ['\\.searchtap\\.io'],
  },
  {
    name: 'Globo Form Builder',
    categories: ['ecommerce-app'],
    website: 'https://globosoftware.net',
    scriptSrc: ['extensions/[^/]+/powerful-form-builder-\\d+/'],
  },
  {
    name: 'Reelfy',
    categories: ['video', 'ecommerce-app'],
    website: 'https://reelfy.io',
    description: 'Shoppable reels and stories',
    scriptSrc: ['extensions/[^/]+/reelfy-\\d+/'],
  },
  {
    name: 'Axon',
    categories: ['advertising', 'ecommerce-app'],
    website: 'https://axon.ai',
    scriptSrc: ['extensions/[^/]+/axon-shop-integration-\\d+/', 's\\.axon\\.ai'],
    requestHost: ['s\\.axon\\.ai'],
  },
  {
    name: 'Okendo Quizzes',
    categories: ['ecommerce-app'],
    website: 'https://www.okendo.io',
    scriptSrc: ['extensions/[^/]+/okendo-[a-z-]*\\d+/'],
    implies: ['Okendo'],
  },
  {
    name: 'Klaviyo Onsite',
    categories: ['marketing-automation', 'ecommerce-app'],
    website: 'https://www.klaviyo.com',
    scriptSrc: ['extensions/[^/]+/klaviyo-[a-z-]*\\d+/'],
    implies: ['Klaviyo'],
  },
  {
    name: 'Yotpo Reviews Widget',
    categories: ['reviews', 'ecommerce-app'],
    website: 'https://www.yotpo.com',
    scriptSrc: ['extensions/[^/]+/yotpo-[a-z-]*\\d+/'],
    implies: ['Yotpo'],
  },
  {
    name: 'Stamped Widget',
    categories: ['reviews', 'ecommerce-app'],
    website: 'https://stamped.io',
    scriptSrc: ['extensions/[^/]+/stamped-[a-z-]*\\d+/'],
    implies: ['Stamped.io'],
  },
  {
    name: 'Tapcart',
    categories: ['ecommerce-app'],
    website: 'https://www.tapcart.com',
    description: 'Native mobile app builder for Shopify',
    requestHost: ['\\.tapcart\\.com'],
    scriptSrc: ['extensions/[^/]+/tapcart-[a-z-]*\\d+/'],
  },
  {
    name: 'Shop Circle',
    categories: ['ecommerce-app'],
    website: 'https://shopcircle.co',
    scriptSrc: ['extensions/[^/]+/(?:appatticserver|shop-circle)-\\d+/'],
  },
  {
    name: 'Klarna On-Site Messaging',
    categories: ['payment', 'ecommerce-app'],
    website: 'https://www.klarna.com',
    scriptSrc: ['extensions/[^/]+/klarna-[a-z-]*\\d+/', 'osm\\.klarnaservices\\.com'],
    implies: ['Klarna'],
  },
];

/** Payment providers outside the US and Western Europe, plus global wallets. */
export const globalPayments: Fingerprint[] = [
  {
    name: 'Mercado Pago',
    categories: ['payment'],
    website: 'https://www.mercadopago.com',
    description: 'Dominant payment provider across Latin America',
    scriptSrc: ['sdk\\.mercadopago\\.com', 'secure\\.mlstatic\\.com'],
    requestHost: ['\\.mercadopago\\.com'],
    js: { MercadoPago: '' },
  },
  {
    name: 'PayU',
    categories: ['payment'],
    website: 'https://payu.com',
    scriptSrc: ['secure\\.payu\\.com', 'jssdk\\.payu\\.in', 'checkout-static\\.payu\\.in'],
    requestHost: ['\\.payu\\.(?:com|in|pl)'],
  },
  {
    name: 'Paystack',
    categories: ['payment'],
    website: 'https://paystack.com',
    description: 'Widely used across Nigeria, Ghana and South Africa',
    scriptSrc: ['js\\.paystack\\.co'],
    js: { PaystackPop: '' },
  },
  {
    name: 'Flutterwave',
    categories: ['payment'],
    website: 'https://flutterwave.com',
    scriptSrc: ['checkout\\.flutterwave\\.com'],
    js: { FlutterwaveCheckout: '' },
  },
  {
    name: 'Midtrans',
    categories: ['payment'],
    website: 'https://midtrans.com',
    description: 'Indonesian payment gateway',
    scriptSrc: ['app\\.(?:sandbox\\.)?midtrans\\.com/snap'],
    js: { snap: { re: '', confidence: 0.4 } },
  },
  {
    name: 'Xendit',
    categories: ['payment'],
    website: 'https://www.xendit.co',
    requestHost: ['\\.xendit\\.co'],
  },
  {
    name: 'dLocal',
    categories: ['payment'],
    website: 'https://dlocal.com',
    scriptSrc: ['js\\.dlocal\\.com'],
  },
  {
    name: 'EBANX',
    categories: ['payment'],
    website: 'https://www.ebanx.com',
    scriptSrc: ['js\\.ebanx\\.com'],
  },
  {
    name: 'Airwallex',
    categories: ['payment'],
    website: 'https://www.airwallex.com',
    scriptSrc: ['checkout\\.airwallex\\.com'],
  },
  {
    name: 'Amazon Pay',
    categories: ['payment'],
    website: 'https://pay.amazon.com',
    scriptSrc: ['static-na\\.payments-amazon\\.com', 'static-eu\\.payments-amazon\\.com'],
    js: { amazon: { re: '', confidence: 0.3 } },
  },
  {
    name: 'Google Pay',
    categories: ['payment'],
    website: 'https://pay.google.com',
    scriptSrc: ['pay\\.google\\.com/gp/p/js/pay\\.js'],
  },
  {
    name: 'Authorize.net',
    categories: ['payment'],
    website: 'https://www.authorize.net',
    scriptSrc: ['js\\.authorize\\.net'],
  },
  {
    name: 'Worldpay',
    categories: ['payment'],
    website: 'https://www.worldpay.com',
    requestHost: ['\\.worldpay\\.com'],
  },
  {
    name: 'Bolt',
    categories: ['payment'],
    website: 'https://www.bolt.com',
    scriptSrc: ['connect\\.bolt\\.com', 'connect-sandbox\\.bolt\\.com'],
    js: { BoltCheckout: '' },
  },
  {
    name: 'Simpl',
    categories: ['payment'],
    website: 'https://getsimpl.com',
    description: 'Buy-now-pay-later, India',
    scriptSrc: ['sdk\\.getsimpl\\.com'],
  },
  {
    name: 'Juspay',
    categories: ['payment'],
    website: 'https://juspay.io',
    scriptSrc: ['sdk\\.juspay\\.in', '\\.juspay\\.io'],
  },
  {
    name: 'Instamojo',
    categories: ['payment'],
    website: 'https://www.instamojo.com',
    scriptSrc: ['js\\.instamojo\\.com'],
  },
  {
    name: 'CCAvenue',
    categories: ['payment'],
    website: 'https://www.ccavenue.com',
    requestHost: ['\\.ccavenue\\.com'],
  },
  {
    name: 'Shiprocket Checkout',
    categories: ['payment'],
    website: 'https://www.shiprocket.in/shiprocket-checkout/',
    scriptSrc: ['fastrr-boost-ui\\.pickrr\\.com', 'checkout\\.shiprocket\\.'],
    implies: ['Shiprocket'],
  },
];

/** Shipping, logistics, returns and tax. */
export const logistics: Fingerprint[] = [
  {
    name: 'ShipStation',
    categories: ['shipping'],
    website: 'https://www.shipstation.com',
    requestHost: ['\\.shipstation\\.com'],
  },
  {
    name: 'Shippo',
    categories: ['shipping'],
    website: 'https://goshippo.com',
    requestHost: ['\\.goshippo\\.com'],
  },
  {
    name: 'Sendcloud',
    categories: ['shipping'],
    website: 'https://www.sendcloud.com',
    requestHost: ['\\.sendcloud\\.(?:sc|com)'],
  },
  {
    name: 'Narvar',
    categories: ['shipping'],
    website: 'https://corp.narvar.com',
    requestHost: ['\\.narvar\\.com'],
  },
  {
    name: 'ReturnGO',
    categories: ['shipping', 'ecommerce-app'],
    website: 'https://returngo.ai',
    requestHost: ['\\.returngo\\.ai'],
  },
  {
    name: 'Delhivery',
    categories: ['shipping'],
    website: 'https://www.delhivery.com',
    requestHost: ['\\.delhivery\\.com'],
  },
  {
    name: 'Nimbuspost',
    categories: ['shipping'],
    website: 'https://nimbuspost.com',
    requestHost: ['\\.nimbuspost\\.com'],
  },
  {
    name: 'ClickPost',
    categories: ['shipping'],
    website: 'https://www.clickpost.ai',
    requestHost: ['\\.clickpost\\.ai'],
  },
  {
    name: 'Avalara',
    categories: ['ecommerce-app'],
    website: 'https://www.avalara.com',
    requestHost: ['\\.avalara\\.(?:com|net)'],
  },
  {
    name: 'TaxJar',
    categories: ['ecommerce-app'],
    website: 'https://www.taxjar.com',
    requestHost: ['\\.taxjar\\.com'],
  },
];

/** Customer data platforms, mobile attribution and engagement seen on large merchants. */
export const merchantGrowth: Fingerprint[] = [
  {
    name: 'MoEngage',
    categories: ['marketing-automation'],
    website: 'https://www.moengage.com',
    scriptSrc: ['cdn\\.moengage\\.com'],
    requestHost: ['\\.moengage\\.com'],
    js: { Moengage: '' },
  },
  {
    name: 'CleverTap',
    categories: ['marketing-automation'],
    website: 'https://clevertap.com',
    scriptSrc: ['d2r1yp2w7bby2u\\.cloudfront\\.net', 'static\\.clevertap\\.com'],
    js: { clevertap: '' },
  },
  {
    name: 'WebEngage',
    categories: ['marketing-automation'],
    website: 'https://webengage.com',
    scriptSrc: ['ssl\\.widgets\\.webengage\\.com', 'cdn\\.widgets\\.webengage\\.com'],
    js: { webengage: '' },
  },
  {
    name: 'mParticle',
    categories: ['analytics'],
    website: 'https://www.mparticle.com',
    scriptSrc: ['jssdkcdns\\.mparticle\\.com'],
    js: { mParticle: '' },
  },
  {
    name: 'Branch',
    categories: ['analytics'],
    website: 'https://www.branch.io',
    description: 'Mobile deep linking and attribution',
    scriptSrc: ['cdn\\.branch\\.io'],
    requestHost: ['\\.app\\.link', 'api\\d?\\.branch\\.io'],
    js: { branch: '' },
  },
  {
    name: 'AppsFlyer',
    categories: ['analytics'],
    website: 'https://www.appsflyer.com',
    requestHost: ['\\.onelink\\.me', '\\.appsflyer\\.com'],
    js: { AF: { re: '', confidence: 0.4 } },
  },
  {
    name: 'Sprinklr',
    categories: ['support', 'chat'],
    website: 'https://www.sprinklr.com',
    requestHost: ['\\.sprinklr\\.com'],
  },
  {
    name: 'Fueled',
    categories: ['analytics'],
    website: 'https://fueled.io',
    description: 'Server-side tracking and conversion APIs for ecommerce',
    requestHost: ['\\.fueled\\.io'],
  },
  {
    name: 'Transcend',
    categories: ['cookie-consent'],
    website: 'https://transcend.io',
    requestHost: ['transcend-cdn\\.com', '\\.transcend\\.io'],
  },
  {
    name: 'AWS WAF',
    categories: ['bot-protection', 'security'],
    website: 'https://aws.amazon.com/waf/',
    requestHost: ['\\.edge\\.sdk\\.awswaf\\.com'],
    html: ['awswaf'],
    implies: ['Amazon Web Services'],
  },
];
