import type { Fingerprint } from '../types.js';

/** JavaScript frameworks, meta-frameworks, static site generators and build tools. */
export const frameworks: Fingerprint[] = [
  {
    name: 'Next.js',
    categories: ['js-framework', 'backend-framework'],
    website: 'https://nextjs.org',
    headers: {
      'x-powered-by': { re: 'Next\\.js\\s*([\\d.]+)?', version: '$1' },
      'x-nextjs-cache': '',
      'x-nextjs-prerender': '',
    },
    html: ['id="__NEXT_DATA__"', '/_next/static/', 'self\\.__next_f', '__next_set_public_path__'],
    scriptSrc: ['/_next/static/chunks/'],
    js: { __NEXT_DATA__: '', next: '' },
    npmDep: ['^next$'],
    implies: ['React', 'Node.js'],
  },
  {
    name: 'Nuxt',
    categories: ['js-framework', 'backend-framework'],
    website: 'https://nuxt.com',
    html: ['window\\.__NUXT__', '/_nuxt/', 'id="__nuxt"', '__nuxt_hydration'],
    scriptSrc: ['/_nuxt/'],
    js: { __NUXT__: '', $nuxt: '' },
    npmDep: ['^nuxt$'],
    implies: ['Vue.js', 'Node.js'],
  },
  {
    name: 'Remix',
    categories: ['js-framework', 'backend-framework'],
    website: 'https://remix.run',
    html: ['window\\.__remixContext', '__remixManifest', '__remixRouteModules'],
    js: { __remixContext: '' },
    npmDep: ['^@remix-run/'],
    implies: ['React', 'Node.js'],
  },
  {
    name: 'React Router',
    categories: ['js-framework'],
    website: 'https://reactrouter.com',
    html: ['__reactRouterContext', '__reactRouterManifest'],
    npmDep: ['^react-router', '^@react-router/'],
    implies: ['React'],
  },
  {
    name: 'SvelteKit',
    categories: ['js-framework', 'backend-framework'],
    website: 'https://kit.svelte.dev',
    html: ['__sveltekit_', 'data-sveltekit-', '/_app/immutable/'],
    scriptSrc: ['/_app/immutable/'],
    npmDep: ['^@sveltejs/kit$'],
    implies: ['Svelte', 'Node.js'],
  },
  {
    name: 'Astro',
    categories: ['js-framework', 'static-site-generator'],
    website: 'https://astro.build',
    meta: { generator: { re: 'Astro\\s*v?([\\d.]+)?', version: '$1' } },
    html: ['astro-island', 'data-astro-cid-', 'astro-slot'],
    npmDep: ['^astro$'],
  },
  {
    name: 'Gatsby',
    categories: ['js-framework', 'static-site-generator'],
    website: 'https://www.gatsbyjs.com',
    meta: { generator: { re: 'Gatsby\\s*([\\d.]+)?', version: '$1' } },
    html: ['id="___gatsby"', '/page-data/app-data\\.json', 'window\\.___webpackCompilationHash'],
    npmDep: ['^gatsby$'],
    implies: ['React'],
  },
  {
    name: 'React',
    categories: ['js-framework', 'ui-framework'],
    website: 'https://react.dev',
    html: ['data-reactroot', 'data-reactid', '__REACT_DEVTOOLS_GLOBAL_HOOK__'],
    js: { 'React.version': { re: '([\\d.]+)', version: '$1' }, __REACT_DEVTOOLS_GLOBAL_HOOK__: '' },
    scriptSrc: [{ re: 'react(?:-dom)?[@/-]v?([\\d.]+).*?\\.js', version: '$1' }],
    npmDep: ['^react$', '^react-dom$'],
  },
  {
    name: 'Vue.js',
    categories: ['js-framework', 'ui-framework'],
    website: 'https://vuejs.org',
    html: ['data-v-app', 'data-v-[0-9a-f]{8}', '__VUE_DEVTOOLS_GLOBAL_HOOK__'],
    js: { 'Vue.version': { re: '([\\d.]+)', version: '$1' }, __VUE__: '' },
    scriptSrc: [{ re: 'vue[@/-]v?([\\d.]+).*?\\.js', version: '$1' }],
    npmDep: ['^vue$'],
  },
  {
    name: 'Angular',
    categories: ['js-framework', 'ui-framework'],
    website: 'https://angular.dev',
    html: [
      { re: 'ng-version="([\\d.]+)"', version: '$1', note: 'Angular emits its exact version' },
      '_nghost-',
      '_ngcontent-',
      'ng-app=',
    ],
    js: { ng: '', 'getAllAngularRootElements': '' },
    npmDep: ['^@angular/core$'],
  },
  {
    name: 'Svelte',
    categories: ['js-framework', 'ui-framework'],
    website: 'https://svelte.dev',
    html: ['class="[^"]*svelte-[0-9a-z]{6}', 'svelte-announcer'],
    npmDep: ['^svelte$'],
  },
  {
    name: 'Preact',
    categories: ['js-framework', 'ui-framework'],
    website: 'https://preactjs.com',
    npmDep: ['^preact$'],
    js: { preact: '' },
  },
  {
    name: 'SolidJS',
    categories: ['js-framework', 'ui-framework'],
    website: 'https://www.solidjs.com',
    npmDep: ['^solid-js$'],
  },
  {
    name: 'Qwik',
    categories: ['js-framework', 'ui-framework'],
    website: 'https://qwik.dev',
    html: ['q:container', 'q:base', 'qwik-loader'],
    npmDep: ['^@builder\\.io/qwik$'],
  },
  {
    name: 'Ember.js',
    categories: ['js-framework'],
    website: 'https://emberjs.com',
    html: ['id="ember\\d+"', 'ember-application', 'ember-view'],
    js: { Ember: { re: '([\\d.]+)', version: '$1' } },
  },
  {
    name: 'Alpine.js',
    categories: ['js-library'],
    website: 'https://alpinejs.dev',
    html: ['\\sx-data=', '\\sx-show=', '\\s@click=', '\\sx-cloak'],
    js: { 'Alpine.version': { re: '([\\d.]+)', version: '$1' }, Alpine: '' },
    scriptSrc: [{ re: 'alpinejs[@/]([\\d.]+)', version: '$1' }, 'alpine(?:\\.min)?\\.js'],
  },
  {
    name: 'htmx',
    categories: ['js-library'],
    website: 'https://htmx.org',
    html: ['\\shx-(?:get|post|target|swap|trigger)='],
    js: { 'htmx.version': { re: '([\\d.]+)', version: '$1' } },
    scriptSrc: [{ re: 'htmx[@.-]?v?([\\d.]+)?(?:/dist)?/?htmx', version: '$1' }, 'htmx(?:\\.min)?\\.js'],
  },
  {
    name: 'Stimulus',
    categories: ['js-library'],
    website: 'https://stimulus.hotwired.dev',
    html: ['\\sdata-controller=', '\\sdata-action='],
    js: { Stimulus: '' },
  },
  {
    name: 'Turbo',
    categories: ['js-library'],
    website: 'https://turbo.hotwired.dev',
    html: ['\\sdata-turbo', 'turbo-frame', 'turbo-stream'],
    js: { Turbo: '' },
  },
  {
    name: 'Lit',
    categories: ['js-library', 'ui-framework'],
    website: 'https://lit.dev',
    html: ['lit\\$[0-9a-f]+\\$', '<!--lit-part'],
    npmDep: ['^lit$', '^lit-element$'],
  },
  {
    name: 'jQuery',
    categories: ['js-library'],
    website: 'https://jquery.com',
    js: { 'jQuery.fn.jquery': { re: '([\\d.]+)', version: '$1' }, jQuery: '' },
    scriptSrc: [
      { re: 'jquery[.-]?(?:core|min)?[.-]?v?(\\d+\\.\\d+(?:\\.\\d+)?)', version: '$1' },
      'jquery(?:\\.min)?\\.js',
    ],
    html: [{ re: 'jquery[.-](\\d+\\.\\d+\\.\\d+)', version: '$1' }],
  },
  {
    name: 'jQuery UI',
    categories: ['js-library'],
    website: 'https://jqueryui.com',
    scriptSrc: [{ re: 'jquery-ui[.-]?(?:min)?[.-]?v?([\\d.]+)?', version: '$1' }],
    implies: ['jQuery'],
  },
  {
    name: 'Backbone.js',
    categories: ['js-library'],
    website: 'https://backbonejs.org',
    js: { 'Backbone.VERSION': { re: '([\\d.]+)', version: '$1' } },
    scriptSrc: ['backbone(?:\\.min)?\\.js'],
  },
  {
    name: 'Vite',
    categories: ['build-tool'],
    website: 'https://vite.dev',
    // The `/assets/index-<hash>.js` convention needs the hash to be a real content hash,
    // otherwise any path containing "assets/index" matches. The loose
    // `type="module" ... /assets/` heuristic was removed: it fires on most modern sites.
    html: ['/@vite/client', '/assets/index-[A-Za-z0-9_-]{8,}\\.js'],
    scriptSrc: ['/@vite/', '/assets/index-[A-Za-z0-9_-]{8,}\\.js'],
    npmDep: ['^vite$'],
  },
  {
    name: 'Webpack',
    categories: ['build-tool'],
    website: 'https://webpack.js.org',
    html: ['webpackJsonp', '__webpack_require__', 'webpackChunk'],
    js: { webpackJsonp: '', __webpack_require__: '' },
  },
  {
    name: 'Turbopack',
    categories: ['build-tool'],
    website: 'https://turbo.build/pack',
    html: ['__turbopack', 'turbopack_load'],
  },
  {
    name: 'Parcel',
    categories: ['build-tool'],
    website: 'https://parceljs.org',
    html: ['parcelRequire'],
    js: { parcelRequire: '' },
  },
  {
    name: 'Hugo',
    categories: ['static-site-generator'],
    website: 'https://gohugo.io',
    meta: { generator: { re: 'Hugo\\s*([\\d.]+)?', version: '$1' } },
  },
  {
    name: 'Jekyll',
    categories: ['static-site-generator'],
    website: 'https://jekyllrb.com',
    meta: { generator: { re: 'Jekyll\\s*v?([\\d.]+)?', version: '$1' } },
    implies: ['Ruby'],
  },
  {
    name: 'Eleventy',
    categories: ['static-site-generator'],
    website: 'https://www.11ty.dev',
    meta: { generator: { re: 'Eleventy\\s*v?([\\d.]+)?', version: '$1' } },
  },
  {
    name: 'Pelican',
    categories: ['static-site-generator'],
    website: 'https://getpelican.com',
    meta: { generator: { re: 'Pelican\\s*([\\d.]+)?', version: '$1' } },
    implies: ['Python'],
  },
];

/** Server-side frameworks, languages and runtimes. */
export const backend: Fingerprint[] = [
  {
    name: 'PHP',
    categories: ['language'],
    website: 'https://www.php.net',
    headers: { 'x-powered-by': { re: 'PHP/?([\\d.]+)?', version: '$1' } },
    cookies: { '^PHPSESSID$': '' },
    url: ['\\.php(?:$|\\?)'],
  },
  {
    name: 'Laravel',
    categories: ['backend-framework'],
    website: 'https://laravel.com',
    cookies: {
      '^laravel_session$': '',
      '^laravel_token$': '',
      // XSRF-TOKEN is the Angular/Axios convention and is set by many non-PHP stacks. On its
      // own it reported Laravel at 94% on wix.com, so it is kept only as weak corroboration.
      '^XSRF-TOKEN$': { re: '', confidence: 0.3 },
    },
    html: ['window\\.Laravel', 'laravel_session'],
    implies: ['PHP'],
  },
  {
    name: 'Symfony',
    categories: ['backend-framework'],
    website: 'https://symfony.com',
    headers: { 'x-debug-token': '', 'x-debug-token-link': '' },
    cookies: { '^sf_redirect$': '', '^symfony$': '' },
    implies: ['PHP'],
  },
  {
    name: 'CodeIgniter',
    categories: ['backend-framework'],
    website: 'https://codeigniter.com',
    cookies: { '^ci_session(?:ion)?$': '' },
    implies: ['PHP'],
  },
  {
    name: 'Yii',
    categories: ['backend-framework'],
    website: 'https://www.yiiframework.com',
    cookies: { '^(?:YII_CSRF_TOKEN|_csrf)$': '' },
    implies: ['PHP'],
  },
  {
    name: 'Ruby',
    categories: ['language'],
    website: 'https://www.ruby-lang.org',
    headers: { 'x-powered-by': { re: 'Phusion Passenger|Ruby' } },
  },
  {
    name: 'Ruby on Rails',
    categories: ['backend-framework'],
    website: 'https://rubyonrails.org',
    headers: { 'x-runtime': '', 'x-request-id': { re: '^[0-9a-f-]{36}$', confidence: 0.2 } },
    meta: { 'csrf-param': 'authenticity_token' },
    // Rails names its session cookie "_<appname>_session". The leading underscore is the
    // discriminator: without it, "laravelcom_session" matched and reported Rails at 94% on
    // laravel.com, a site with no Ruby in it at all.
    cookies: { '^_[a-zA-Z0-9]+_session$': '', '^_rails': '' },
    html: ['name="authenticity_token"', '/assets/application-[0-9a-f]{32,64}\\.js'],
    implies: ['Ruby'],
  },
  {
    name: 'Python',
    categories: ['language'],
    website: 'https://www.python.org',
    headers: { server: 'Werkzeug|gunicorn|uvicorn|WSGIServer|Python' },
  },
  {
    name: 'Django',
    categories: ['backend-framework'],
    website: 'https://www.djangoproject.com',
    cookies: { '^csrftoken$': '', '^django_language$': '', '^sessionid$': '' },
    html: ['name="csrfmiddlewaretoken"', '/static/admin/'],
    probe: [{ path: '/admin/login/', body: 'csrfmiddlewaretoken|Django site admin' }],
    implies: ['Python'],
  },
  {
    name: 'Flask',
    categories: ['backend-framework'],
    website: 'https://flask.palletsprojects.com',
    headers: { server: 'Werkzeug/?([\\d.]+)?' },
    implies: ['Python'],
  },
  {
    name: 'FastAPI',
    categories: ['backend-framework'],
    website: 'https://fastapi.tiangolo.com',
    probe: [
      { path: '/openapi.json', body: '"openapi"\\s*:\\s*"3' },
      { path: '/docs', body: 'swagger-ui|FastAPI' },
    ],
    implies: ['Python'],
  },
  {
    name: 'Node.js',
    categories: ['runtime'],
    website: 'https://nodejs.org',
    headers: { 'x-powered-by': 'Express|Next\\.js|Nuxt|Koa|Fastify|Nest' },
  },
  {
    name: 'Express',
    categories: ['backend-framework'],
    website: 'https://expressjs.com',
    headers: { 'x-powered-by': '^Express$' },
    implies: ['Node.js'],
  },
  {
    name: 'Fastify',
    categories: ['backend-framework'],
    website: 'https://fastify.dev',
    headers: { 'x-powered-by': 'Fastify' },
    implies: ['Node.js'],
  },
  {
    name: 'NestJS',
    categories: ['backend-framework'],
    website: 'https://nestjs.com',
    headers: { 'x-powered-by': 'Nest' },
    implies: ['Node.js'],
  },
  {
    name: 'Hono',
    categories: ['backend-framework'],
    website: 'https://hono.dev',
    npmDep: ['^hono$'],
  },
  {
    name: 'ASP.NET',
    categories: ['backend-framework'],
    website: 'https://dotnet.microsoft.com/apps/aspnet',
    headers: {
      'x-aspnet-version': { re: '([\\d.]+)', version: '$1' },
      'x-aspnetmvc-version': { re: '([\\d.]+)', version: '$1' },
      'x-powered-by': 'ASP\\.NET',
    },
    cookies: { '^ASP\\.NET_SessionId$': '', '^\\.AspNetCore\\.': '' },
    html: ['id="__VIEWSTATE"', '__doPostBack', 'id="__EVENTVALIDATION"'],
  },
  {
    name: 'Blazor',
    categories: ['js-framework'],
    website: 'https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor',
    html: ['_framework/blazor', '_blazor'],
    implies: ['ASP.NET'],
  },
  {
    name: 'Java',
    categories: ['language'],
    website: 'https://www.java.com',
    cookies: { '^JSESSIONID$': '' },
    url: ['\\.(?:jsp|do|jsf)(?:$|\\?)'],
  },
  {
    name: 'Spring',
    categories: ['backend-framework'],
    website: 'https://spring.io',
    cookies: { '^SPRING_SECURITY_REMEMBER_ME': '' },
    probe: [{ path: '/actuator/health', body: '"status"\\s*:\\s*"(?:UP|DOWN)"' }],
    implies: ['Java'],
  },
  {
    name: 'Phoenix',
    categories: ['backend-framework'],
    website: 'https://www.phoenixframework.org',
    html: ['phx-(?:socket|main|hook|click)', 'data-phx-'],
    cookies: { '_key$': { re: '', confidence: 0.3 } },
    implies: ['Elixir'],
  },
  {
    name: 'Elixir',
    categories: ['language'],
    website: 'https://elixir-lang.org',
    headers: { server: 'Cowboy|bandit' },
  },
  {
    name: 'Go',
    categories: ['language'],
    website: 'https://go.dev',
    headers: { server: 'Go-http-client|Caddy' },
  },
];

/** HTTP servers and application servers. */
export const servers: Fingerprint[] = [
  {
    name: 'Nginx',
    categories: ['web-server'],
    website: 'https://nginx.org',
    headers: { server: { re: 'nginx(?:/([\\d.]+))?', version: '$1' } },
  },
  {
    name: 'Apache HTTP Server',
    categories: ['web-server'],
    website: 'https://httpd.apache.org',
    headers: { server: { re: 'Apache(?:/([\\d.]+))?', version: '$1' } },
  },
  {
    name: 'LiteSpeed',
    categories: ['web-server'],
    website: 'https://www.litespeedtech.com',
    headers: { server: 'LiteSpeed', 'x-litespeed-cache': '' },
  },
  {
    name: 'Microsoft IIS',
    categories: ['web-server'],
    website: 'https://www.iis.net',
    headers: { server: { re: 'Microsoft-IIS/([\\d.]+)', version: '$1' } },
  },
  {
    name: 'Caddy',
    categories: ['web-server'],
    website: 'https://caddyserver.com',
    headers: { server: 'Caddy' },
  },
  {
    name: 'OpenResty',
    categories: ['web-server'],
    website: 'https://openresty.org',
    headers: { server: { re: 'openresty(?:/([\\d.]+))?', version: '$1' } },
    implies: ['Nginx', 'Lua'],
  },
  { name: 'Lua', categories: ['language'], website: 'https://www.lua.org' },
  {
    name: 'Envoy',
    categories: ['web-server'],
    website: 'https://www.envoyproxy.io',
    headers: { server: 'envoy', 'x-envoy-upstream-service-time': '' },
  },
  {
    name: 'Gunicorn',
    categories: ['web-server'],
    website: 'https://gunicorn.org',
    headers: { server: { re: 'gunicorn(?:/([\\d.]+))?', version: '$1' } },
    implies: ['Python'],
  },
  {
    name: 'Uvicorn',
    categories: ['web-server'],
    website: 'https://www.uvicorn.org',
    headers: { server: 'uvicorn' },
    implies: ['Python'],
  },
  {
    name: 'Puma',
    categories: ['web-server'],
    website: 'https://puma.io',
    headers: { server: 'Puma' },
    implies: ['Ruby'],
  },
  {
    name: 'Apache Tomcat',
    categories: ['web-server'],
    website: 'https://tomcat.apache.org',
    headers: { server: { re: 'Apache-Coyote|Tomcat(?:/([\\d.]+))?', version: '$1' } },
    implies: ['Java'],
  },
  {
    name: 'Kestrel',
    categories: ['web-server'],
    website: 'https://learn.microsoft.com/aspnet/core/fundamentals/servers/kestrel',
    headers: { server: 'Kestrel' },
    implies: ['ASP.NET'],
  },
  {
    name: 'Varnish',
    categories: ['web-server', 'cdn'],
    website: 'https://varnish-cache.org',
    headers: { 'x-varnish': '', via: 'varnish' },
  },
  {
    name: 'MySQL',
    categories: ['database'],
    website: 'https://www.mysql.com',
  },
  {
    name: 'PostgreSQL',
    categories: ['database'],
    website: 'https://www.postgresql.org',
  },
];
