import type { Fingerprint } from '../types.js';

/**
 * CSS and component frameworks.
 *
 * These are the hardest category to detect well, because compiled CSS erases most of the
 * evidence. The reliable signals are generated class-name conventions (`MuiBox-root`,
 * `chakra-`, `--tw-`) and dependency names recovered from sourcemaps, so those are weighted
 * ahead of loose utility-class guesses.
 */
export const ui: Fingerprint[] = [
  {
    name: 'Tailwind CSS',
    categories: ['css-framework'],
    website: 'https://tailwindcss.com',
    // Detected from compiled CSS, not from class names. Utility class names like
    // "flex items-center" are trivially reproducible by hand and produce false positives on
    // any hand-rolled utility system, so they are deliberately not used as evidence.
    cssContent: [
      { re: '--tw-(?:ring-inset|shadow-colored|translate-x|gradient-from|space-y-reverse)', note: 'Tailwind generated custom properties' },
      { re: '\\*,\\s*::before,\\s*::after\\s*\\{[^}]*--tw-', note: 'Tailwind preflight block' },
    ],
    html: [
      { re: '--tw-(?:ring|shadow|translate|gradient|space|border)-', confidence: 0.8, note: 'Tailwind custom property in inline style' },
    ],
    stylesheetSrc: ['tailwind'],
    npmDep: ['^tailwindcss$'],
  },
  {
    name: 'Bootstrap',
    categories: ['css-framework'],
    website: 'https://getbootstrap.com',
    stylesheetSrc: [{ re: 'bootstrap[@/-]?v?(\\d+\\.\\d+(?:\\.\\d+)?)?[^/]*\\.(?:min\\.)?css', version: '$1' }],
    scriptSrc: [{ re: 'bootstrap[@/-]?v?(\\d+\\.\\d+(?:\\.\\d+)?)?[^/]*\\.(?:bundle\\.)?(?:min\\.)?js', version: '$1' }],
    cssContent: [
      { re: '--bs-(?:blue|primary|body-bg|gutter-x)', note: 'Bootstrap 5 CSS variables' },
      { re: 'Bootstrap\\s+v(\\d+\\.\\d+\\.\\d+)', version: '$1', note: 'Bootstrap banner comment' },
    ],
    html: [{ re: 'class="[^"]*\\b(?:col-(?:xs|sm|md|lg|xl)-\\d+|navbar-toggler|carousel-inner)\\b', confidence: 0.5 }],
    js: { 'bootstrap.Tooltip': '' },
    npmDep: ['^bootstrap$'],
  },
  {
    name: 'Bulma',
    categories: ['css-framework'],
    website: 'https://bulma.io',
    stylesheetSrc: [{ re: 'bulma[@/-]?v?([\\d.]+)?[^/]*\\.(?:min\\.)?css', version: '$1' }],
    cssContent: [{ re: 'bulma(?:\\.io)?[^\\n]{0,40}v?(\\d+\\.\\d+\\.\\d+)', version: '$1' }, '--bulma-'],
    html: [{ re: 'class="[^"]*\\b(?:is-primary|hero-body)\\b[^"]*"[\\s\\S]{0,400}class="[^"]*\\bcolumn is-', confidence: 0.45 }],
  },
  {
    name: 'Foundation',
    categories: ['css-framework'],
    website: 'https://get.foundation',
    stylesheetSrc: ['foundation(?:\\.min)?\\.css'],
    cssContent: ['foundation(?:\\s+for\\s+sites)?\\s+v?\\d'],
    html: [{ re: 'class="[^"]*\\bsmall-\\d+\\s+(?:medium|large)-\\d+\\b', confidence: 0.5 }],
  },
  {
    name: 'Material UI',
    categories: ['ui-framework'],
    website: 'https://mui.com',
    html: ['\\bMui[A-Z][A-Za-z]+-(?:root|primary)', 'css-[a-z0-9]+-Mui'],
    npmDep: ['^@mui/', '^@material-ui/'],
    implies: ['React', 'Emotion'],
  },
  {
    name: 'Chakra UI',
    categories: ['ui-framework'],
    website: 'https://chakra-ui.com',
    html: ['class="[^"]*\\bchakra-[a-z]+', 'data-theme="(?:light|dark)"[^>]*class="[^"]*chakra'],
    npmDep: ['^@chakra-ui/'],
    implies: ['React'],
  },
  {
    name: 'Ant Design',
    categories: ['ui-framework'],
    website: 'https://ant.design',
    html: ['class="[^"]*\\bant-(?:btn|layout|menu|row|col)\\b'],
    npmDep: ['^antd$'],
    implies: ['React'],
  },
  {
    name: 'Mantine',
    categories: ['ui-framework'],
    website: 'https://mantine.dev',
    html: ['class="[^"]*\\bmantine-', 'data-mantine-'],
    npmDep: ['^@mantine/'],
    implies: ['React'],
  },
  {
    name: 'Radix UI',
    categories: ['ui-framework'],
    website: 'https://www.radix-ui.com',
    html: ['data-radix-', '\\bradix-:r[0-9a-z]+:'],
    npmDep: ['^@radix-ui/'],
    implies: ['React'],
  },
  {
    name: 'shadcn/ui',
    categories: ['ui-framework'],
    website: 'https://ui.shadcn.com',
    npmDep: ['^class-variance-authority$', '^tailwind-merge$'],
    requires: ['Radix UI'],
    implies: ['Radix UI', 'Tailwind CSS'],
    description: 'Radix primitives styled with Tailwind, copied into the project',
  },
  {
    name: 'Headless UI',
    categories: ['ui-framework'],
    website: 'https://headlessui.com',
    html: ['\\bheadlessui-', 'id="headlessui-'],
    npmDep: ['^@headlessui/'],
  },
  {
    name: 'DaisyUI',
    categories: ['css-framework'],
    website: 'https://daisyui.com',
    html: ['class="[^"]*\\b(?:btn-primary|card-body|navbar-start|drawer-toggle)\\b'],
    npmDep: ['^daisyui$'],
    implies: ['Tailwind CSS'],
  },
  {
    name: 'Vuetify',
    categories: ['ui-framework'],
    website: 'https://vuetifyjs.com',
    html: ['class="[^"]*\\bv-application\\b', 'class="[^"]*\\bv-(?:btn|card|container)\\b'],
    npmDep: ['^vuetify$'],
    implies: ['Vue.js'],
  },
  {
    name: 'Element Plus',
    categories: ['ui-framework'],
    website: 'https://element-plus.org',
    html: ['class="[^"]*\\bel-(?:button|row|col|input)\\b'],
    npmDep: ['^element-plus$'],
    implies: ['Vue.js'],
  },
  {
    name: 'PrimeVue',
    categories: ['ui-framework'],
    website: 'https://primevue.org',
    html: ['class="[^"]*\\bp-(?:component|button|inputtext)\\b'],
    npmDep: ['^primevue$'],
  },
  {
    name: 'Quasar',
    categories: ['ui-framework'],
    website: 'https://quasar.dev',
    html: ['class="[^"]*\\bq-(?:btn|layout|page)\\b'],
    npmDep: ['^quasar$'],
    implies: ['Vue.js'],
  },
  {
    name: 'Ionic',
    categories: ['ui-framework'],
    website: 'https://ionicframework.com',
    html: ['<ion-(?:app|content|button)', 'class="[^"]*\\bion-'],
    npmDep: ['^@ionic/'],
  },
  {
    name: 'styled-components',
    categories: ['css-framework'],
    website: 'https://styled-components.com',
    html: ['data-styled(?:-version)?=', '\\bsc-[a-zA-Z0-9]{6,}\\b'],
    npmDep: ['^styled-components$'],
  },
  {
    name: 'Emotion',
    categories: ['css-framework'],
    website: 'https://emotion.sh',
    html: ['data-emotion=', 'class="[^"]*\\bcss-[a-z0-9]{6,}\\b'],
    npmDep: ['^@emotion/'],
  },
  {
    name: 'UnoCSS',
    categories: ['css-framework'],
    website: 'https://unocss.dev',
    html: ['/__unocss', 'data-unocss'],
    npmDep: ['^unocss$'],
  },
];

/** General-purpose JavaScript libraries. */
export const libraries: Fingerprint[] = [
  {
    name: 'Lodash',
    categories: ['js-library'],
    website: 'https://lodash.com',
    js: { 'VERSION': { re: '^([\\d.]+)$', confidence: 0.2 }, '_.VERSION': { re: '([\\d.]+)', version: '$1' } },
    scriptSrc: [{ re: 'lodash[@/.-]?v?([\\d.]+)?[^/]*\\.js', version: '$1' }],
    npmDep: ['^lodash$', '^lodash-es$'],
  },
  {
    name: 'Underscore.js',
    categories: ['js-library'],
    website: 'https://underscorejs.org',
    scriptSrc: ['underscore(?:\\.min)?\\.js'],
  },
  {
    name: 'Moment.js',
    categories: ['js-library'],
    website: 'https://momentjs.com',
    js: { 'moment.version': { re: '([\\d.]+)', version: '$1' } },
    scriptSrc: [{ re: 'moment[@/.-]?v?([\\d.]+)?[^/]*\\.js', version: '$1' }],
    npmDep: ['^moment$'],
  },
  {
    name: 'Day.js',
    categories: ['js-library'],
    website: 'https://day.js.org',
    scriptSrc: [{ re: 'dayjs[@/]([\\d.]+)?', version: '$1' }, 'dayjs(?:\\.min)?\\.js'],
    npmDep: ['^dayjs$'],
  },
  {
    name: 'date-fns',
    categories: ['js-library'],
    website: 'https://date-fns.org',
    npmDep: ['^date-fns$'],
  },
  {
    name: 'Axios',
    categories: ['js-library'],
    website: 'https://axios-http.com',
    scriptSrc: [{ re: 'axios[@/]([\\d.]+)?', version: '$1' }, 'axios(?:\\.min)?\\.js'],
    js: { 'axios.VERSION': { re: '([\\d.]+)', version: '$1' }, axios: '' },
    npmDep: ['^axios$'],
  },
  {
    name: 'Swiper',
    categories: ['js-library'],
    website: 'https://swiperjs.com',
    scriptSrc: [{ re: 'swiper[@/]v?(\\d+(?:\\.\\d+)*)', version: '$1' }, 'swiper-bundle'],
    stylesheetSrc: ['swiper'],
    html: ['swiper-(?:container|wrapper|slide)', 'class="[^"]*\\bswiper\\b'],
    npmDep: ['^swiper$'],
  },
  {
    name: 'Slick Carousel',
    categories: ['js-library'],
    website: 'https://kenwheeler.github.io/slick/',
    scriptSrc: ['slick(?:\\.min)?\\.js', 'slick/slick'],
    stylesheetSrc: ['slick(?:-theme)?(?:\\.min)?\\.css'],
    html: ['class="[^"]*\\bslick-(?:slider|track|slide)\\b'],
    implies: ['jQuery'],
  },
  {
    name: 'Splide',
    categories: ['js-library'],
    website: 'https://splidejs.com',
    scriptSrc: [{ re: '@splidejs/splide@([\\d.]+)', version: '$1' }, 'splide(?:\\.min)?\\.js'],
    html: ['class="[^"]*\\bsplide\\b', 'splide__(?:track|list|slide)'],
    npmDep: ['^@splidejs/'],
  },
  {
    name: 'Flickity',
    categories: ['js-library'],
    website: 'https://flickity.metafizzy.co',
    scriptSrc: ['flickity(?:\\.pkgd)?(?:\\.min)?\\.js'],
    html: ['class="[^"]*\\bflickity-'],
  },
  {
    name: 'Embla Carousel',
    categories: ['js-library'],
    website: 'https://www.embla-carousel.com',
    npmDep: ['^embla-carousel'],
    html: ['embla__(?:container|slide)'],
  },
  {
    name: 'GSAP',
    categories: ['js-library'],
    website: 'https://gsap.com',
    scriptSrc: [{ re: 'gsap[@/]([\\d.]+)?', version: '$1' }, 'gsap(?:\\.min)?\\.js', 'TweenMax'],
    js: { 'gsap.version': { re: '([\\d.]+)', version: '$1' }, gsap: '' },
    npmDep: ['^gsap$'],
  },
  {
    name: 'Framer Motion',
    categories: ['js-library'],
    website: 'https://motion.dev',
    npmDep: ['^framer-motion$', '^motion$'],
    implies: ['React'],
  },
  {
    name: 'Lottie',
    categories: ['js-library'],
    website: 'https://airbnb.io/lottie/',
    scriptSrc: ['lottie(?:-player|_svg|_light)?(?:\\.min)?\\.js'],
    html: ['<lottie-player', 'dotlottie'],
    npmDep: ['^lottie-'],
  },
  {
    name: 'Three.js',
    categories: ['js-library'],
    website: 'https://threejs.org',
    scriptSrc: [{ re: 'three[@/](?:r|v)?([\\d.]+)?', version: '$1' }, 'three(?:\\.module|\\.min)?\\.js'],
    js: { 'THREE.REVISION': { re: '(\\d+)', version: '$1' }, THREE: '' },
    npmDep: ['^three$'],
  },
  {
    name: 'D3.js',
    categories: ['js-library'],
    website: 'https://d3js.org',
    scriptSrc: [{ re: '(?:^|[/@])d3(?:-[a-z]+)?(?:@|[/.-]v?)?(\\d+(?:\\.\\d+)*)?(?:\\.min)?\\.js', version: '$1' }],
    js: { 'd3.version': { re: '([\\d.]+)', version: '$1' } },
    npmDep: ['^d3$', '^d3-'],
  },
  {
    name: 'Chart.js',
    categories: ['js-library'],
    website: 'https://www.chartjs.org',
    scriptSrc: [{ re: 'chart\\.?js[@/]?v?([\\d.]+)?', version: '$1' }],
    js: { 'Chart.version': { re: '([\\d.]+)', version: '$1' }, Chart: '' },
    npmDep: ['^chart\\.js$'],
  },
  {
    name: 'ECharts',
    categories: ['js-library'],
    website: 'https://echarts.apache.org',
    scriptSrc: ['echarts(?:\\.min)?\\.js'],
    js: { 'echarts.version': { re: '([\\d.]+)', version: '$1' } },
    npmDep: ['^echarts$'],
  },
  {
    name: 'Highcharts',
    categories: ['js-library'],
    website: 'https://www.highcharts.com',
    scriptSrc: ['highcharts(?:\\.min)?\\.js', 'code\\.highcharts\\.com'],
    js: { 'Highcharts.version': { re: '([\\d.]+)', version: '$1' } },
  },
  {
    name: 'ApexCharts',
    categories: ['js-library'],
    website: 'https://apexcharts.com',
    scriptSrc: ['apexcharts(?:\\.min)?\\.js'],
    npmDep: ['^apexcharts$'],
  },
  {
    name: 'Recharts',
    categories: ['js-library'],
    website: 'https://recharts.org',
    npmDep: ['^recharts$'],
    html: ['recharts-(?:wrapper|surface)'],
  },
  {
    name: 'TanStack Query',
    categories: ['js-library'],
    website: 'https://tanstack.com/query',
    npmDep: ['^@tanstack/(?:react-|vue-|svelte-)?query$', '^react-query$'],
  },
  {
    name: 'Redux',
    categories: ['js-library'],
    website: 'https://redux.js.org',
    js: { __REDUX_DEVTOOLS_EXTENSION__: '' },
    npmDep: ['^redux$', '^@reduxjs/toolkit$'],
  },
  {
    name: 'Zustand',
    categories: ['js-library'],
    website: 'https://zustand.docs.pmnd.rs',
    npmDep: ['^zustand$'],
  },
  {
    name: 'Pinia',
    categories: ['js-library'],
    website: 'https://pinia.vuejs.org',
    npmDep: ['^pinia$'],
    implies: ['Vue.js'],
  },
  {
    name: 'Apollo Client',
    categories: ['js-library'],
    website: 'https://www.apollographql.com/docs/react/',
    npmDep: ['^@apollo/client$'],
    implies: ['GraphQL'],
  },
  {
    name: 'GraphQL',
    categories: ['js-library'],
    website: 'https://graphql.org',
    npmDep: ['^graphql$'],
    probe: [
      { path: '/graphql', status: [200, 400, 405], body: '"errors"\\s*:\\s*\\[|graphql-playground|GraphQL request' },
      { path: '/api/graphql', status: [200, 400, 405], body: '"errors"\\s*:\\s*\\[|GraphQL request' },
    ],
  },
  {
    name: 'tRPC',
    categories: ['js-library'],
    website: 'https://trpc.io',
    npmDep: ['^@trpc/'],
  },
  {
    name: 'Zod',
    categories: ['js-library'],
    website: 'https://zod.dev',
    npmDep: ['^zod$'],
  },
  {
    name: 'Modernizr',
    categories: ['js-library'],
    website: 'https://modernizr.com',
    scriptSrc: ['modernizr'],
    js: { 'Modernizr._version': { re: '([\\d.]+)', version: '$1' }, Modernizr: '' },
  },
  {
    name: 'Popper.js',
    categories: ['js-library'],
    website: 'https://popper.js.org',
    scriptSrc: ['popper(?:\\.min)?\\.js', '@popperjs/core'],
    npmDep: ['^@popperjs/'],
  },
  {
    name: 'Tippy.js',
    categories: ['js-library'],
    website: 'https://atomiks.github.io/tippyjs/',
    scriptSrc: ['tippy(?:\\.min|\\.umd)?\\.js'],
    npmDep: ['^tippy\\.js$'],
  },
  {
    name: 'Floating UI',
    categories: ['js-library'],
    website: 'https://floating-ui.com',
    npmDep: ['^@floating-ui/'],
  },
  {
    name: 'SortableJS',
    categories: ['js-library'],
    website: 'https://sortablejs.github.io/Sortable/',
    scriptSrc: ['[Ss]ortable(?:\\.min)?\\.js'],
    npmDep: ['^sortablejs$'],
  },
  {
    name: 'AOS',
    categories: ['js-library'],
    website: 'https://michalsnik.github.io/aos/',
    scriptSrc: ['aos(?:\\.min)?\\.js'],
    html: ['\\sdata-aos='],
  },
  {
    name: 'Lenis',
    categories: ['js-library'],
    website: 'https://lenis.darkroom.engineering',
    npmDep: ['^(?:@studio-freight/)?lenis$'],
    html: ['\\blenis(?:-|\\s|")'],
  },
  {
    name: 'Locomotive Scroll',
    categories: ['js-library'],
    website: 'https://locomotivemtl.github.io/locomotive-scroll/',
    scriptSrc: ['locomotive-scroll'],
    html: ['\\sdata-scroll(?:-|=|>)'],
  },
  {
    name: 'SweetAlert2',
    categories: ['js-library'],
    website: 'https://sweetalert2.github.io',
    scriptSrc: ['sweetalert2'],
    js: { Swal: '' },
  },
  {
    name: 'NProgress',
    categories: ['js-library'],
    website: 'https://ricostacruz.com/nprogress/',
    scriptSrc: ['nprogress(?:\\.min)?\\.js'],
    js: { NProgress: '' },
  },
  {
    name: 'Fancybox',
    categories: ['js-library'],
    website: 'https://fancyapps.com/fancybox/',
    scriptSrc: ['(?:jquery\\.)?fancybox'],
    html: ['data-fancybox'],
  },
  {
    name: 'PhotoSwipe',
    categories: ['js-library'],
    website: 'https://photoswipe.com',
    scriptSrc: ['photoswipe'],
    npmDep: ['^photoswipe$'],
  },
  {
    name: 'Flatpickr',
    categories: ['js-library'],
    website: 'https://flatpickr.js.org',
    scriptSrc: ['flatpickr'],
    js: { flatpickr: '' },
  },
  {
    name: 'FullCalendar',
    categories: ['js-library'],
    website: 'https://fullcalendar.io',
    scriptSrc: ['fullcalendar'],
    npmDep: ['^@fullcalendar/'],
  },
  {
    name: 'Select2',
    categories: ['js-library'],
    website: 'https://select2.org',
    scriptSrc: ['select2(?:\\.full)?(?:\\.min)?\\.js'],
    implies: ['jQuery'],
  },
  {
    name: 'Prism',
    categories: ['js-library'],
    website: 'https://prismjs.com',
    scriptSrc: ['prism(?:\\.min)?\\.js'],
    html: ['class="[^"]*\\blanguage-[a-z]+\\b[^"]*"[^>]*>|token comment'],
  },
  {
    name: 'highlight.js',
    categories: ['js-library'],
    website: 'https://highlightjs.org',
    scriptSrc: ['highlight(?:\\.min|\\.pack)?\\.js'],
    js: { hljs: '' },
  },
  {
    name: 'Shiki',
    categories: ['js-library'],
    website: 'https://shiki.style',
    html: ['class="[^"]*\\bshiki\\b', 'data-shiki'],
    npmDep: ['^shiki$'],
  },
  {
    name: 'CodeMirror',
    categories: ['js-library'],
    website: 'https://codemirror.net',
    html: ['class="[^"]*\\bcm-(?:editor|content)\\b', 'CodeMirror'],
    npmDep: ['^@codemirror/', '^codemirror$'],
  },
  {
    name: 'Monaco Editor',
    categories: ['js-library'],
    website: 'https://microsoft.github.io/monaco-editor/',
    scriptSrc: ['monaco-editor'],
    html: ['monaco-editor'],
  },
  {
    name: 'TinyMCE',
    categories: ['js-library'],
    website: 'https://www.tiny.cloud',
    scriptSrc: ['tinymce(?:\\.min)?\\.js', 'cdn\\.tiny\\.cloud'],
    js: { tinymce: '' },
  },
  {
    name: 'CKEditor',
    categories: ['js-library'],
    website: 'https://ckeditor.com',
    scriptSrc: ['ckeditor'],
    js: { CKEDITOR: '' },
  },
  {
    name: 'Tiptap',
    categories: ['js-library'],
    website: 'https://tiptap.dev',
    npmDep: ['^@tiptap/'],
    html: ['class="[^"]*\\btiptap\\b', 'ProseMirror'],
  },
];

/** Maps, media, video and asset delivery. */
export const media: Fingerprint[] = [
  {
    name: 'Google Maps',
    categories: ['maps'],
    website: 'https://developers.google.com/maps',
    scriptSrc: ['maps\\.google(?:apis)?\\.com/maps/api'],
    html: ['maps\\.google\\.com/maps', 'google\\.maps\\.'],
  },
  {
    name: 'Mapbox',
    categories: ['maps'],
    website: 'https://www.mapbox.com',
    scriptSrc: ['api\\.mapbox\\.com', 'mapbox-gl'],
    js: { mapboxgl: '' },
    npmDep: ['^mapbox-gl$'],
  },
  {
    name: 'Leaflet',
    categories: ['maps'],
    website: 'https://leafletjs.com',
    scriptSrc: [{ re: 'leaflet[@/]?v?([\\d.]+)?[^/]*\\.js', version: '$1' }],
    js: { 'L.version': { re: '([\\d.]+)', version: '$1' } },
  },
  {
    name: 'OpenStreetMap',
    categories: ['maps'],
    website: 'https://www.openstreetmap.org',
    html: ['tile\\.openstreetmap\\.org'],
  },
  {
    name: 'Cloudinary',
    categories: ['media'],
    website: 'https://cloudinary.com',
    html: ['res\\.cloudinary\\.com'],
    requestHost: ['res\\.cloudinary\\.com'],
  },
  {
    name: 'imgix',
    categories: ['media'],
    website: 'https://www.imgix.com',
    html: ['\\.imgix\\.net'],
    requestHost: ['\\.imgix\\.net'],
  },
  {
    name: 'ImageKit',
    categories: ['media'],
    website: 'https://imagekit.io',
    html: ['ik\\.imagekit\\.io'],
    requestHost: ['ik\\.imagekit\\.io'],
  },
  {
    name: 'Uploadcare',
    categories: ['media'],
    website: 'https://uploadcare.com',
    html: ['ucarecdn\\.com'],
  },
  {
    name: 'Mux',
    categories: ['video'],
    website: 'https://www.mux.com',
    html: ['stream\\.mux\\.com', 'image\\.mux\\.com'],
    npmDep: ['^@mux/'],
  },
  {
    name: 'Vimeo',
    categories: ['video'],
    website: 'https://vimeo.com',
    html: ['player\\.vimeo\\.com'],
  },
  {
    name: 'YouTube',
    categories: ['video'],
    website: 'https://www.youtube.com',
    html: ['(?:www\\.)?youtube(?:-nocookie)?\\.com/embed', 'youtu\\.be/'],
  },
  {
    name: 'Wistia',
    categories: ['video'],
    website: 'https://wistia.com',
    scriptSrc: ['fast\\.wistia\\.(?:com|net)'],
    js: { Wistia: '' },
  },
  {
    name: 'Video.js',
    categories: ['video'],
    website: 'https://videojs.com',
    scriptSrc: ['video(?:\\.min)?\\.js', 'videojs'],
    js: { videojs: '' },
  },
  {
    name: 'Plyr',
    categories: ['video'],
    website: 'https://plyr.io',
    scriptSrc: ['plyr(?:\\.min|\\.polyfilled)?\\.js'],
    js: { Plyr: '' },
  },
  {
    name: 'HLS.js',
    categories: ['video'],
    website: 'https://github.com/video-dev/hls.js',
    scriptSrc: ['hls(?:\\.min|\\.light)?\\.js'],
    js: { Hls: '' },
  },
  {
    name: 'Cloudflare Stream',
    categories: ['video'],
    website: 'https://www.cloudflare.com/products/cloudflare-stream/',
    html: ['(?:videodelivery\\.net|customer-[a-z0-9]+\\.cloudflarestream\\.com)'],
    implies: ['Cloudflare'],
  },
];

/** Web fonts and icon sets. */
export const fonts: Fingerprint[] = [
  {
    name: 'Google Fonts',
    categories: ['font'],
    website: 'https://fonts.google.com',
    stylesheetSrc: ['fonts\\.googleapis\\.com'],
    html: ['fonts\\.googleapis\\.com', 'fonts\\.gstatic\\.com'],
    requestHost: ['fonts\\.(?:googleapis|gstatic)\\.com'],
  },
  {
    name: 'Adobe Fonts',
    categories: ['font'],
    website: 'https://fonts.adobe.com',
    html: ['use\\.typekit\\.net', 'p\\.typekit\\.net'],
    scriptSrc: ['use\\.typekit\\.net'],
  },
  {
    name: 'Font Awesome',
    categories: ['font'],
    website: 'https://fontawesome.com',
    stylesheetSrc: [{ re: 'font-?awesome[^"]*?([\\d.]+)?[^/]*\\.css', version: '$1' }],
    scriptSrc: ['kit\\.fontawesome\\.com', 'fontawesome'],
    html: ['class="[^"]*\\bfa[srlbd]?\\s+fa-', 'class="[^"]*\\bfa-[a-z-]+'],
  },
  {
    name: 'Bunny Fonts',
    categories: ['font'],
    website: 'https://fonts.bunny.net',
    stylesheetSrc: ['fonts\\.bunny\\.net'],
  },
  {
    name: 'Fontshare',
    categories: ['font'],
    website: 'https://www.fontshare.com',
    stylesheetSrc: ['api\\.fontshare\\.com'],
  },
  {
    name: 'Iconify',
    categories: ['font'],
    website: 'https://iconify.design',
    scriptSrc: ['iconify'],
    html: ['<iconify-icon', 'api\\.iconify\\.design'],
  },
];

/** Miscellaneous widely deployed services. */
export const misc: Fingerprint[] = [
  {
    name: 'Google Translate Widget',
    categories: ['translation'],
    website: 'https://translate.google.com',
    scriptSrc: ['translate\\.google(?:apis)?\\.com/translate_a/element\\.js'],
    js: { google_translate_element: '' },
  },
  {
    name: 'Weglot',
    categories: ['translation'],
    website: 'https://weglot.com',
    scriptSrc: ['cdn\\.weglot\\.com'],
    js: { Weglot: '' },
  },
  {
    name: 'Crowdin',
    categories: ['translation'],
    website: 'https://crowdin.com',
    scriptSrc: ['cdn\\.crowdin\\.com'],
  },
  {
    name: 'accessiBe',
    categories: ['accessibility'],
    website: 'https://accessibe.com',
    scriptSrc: ['acsbapp\\.com', 'accessibe'],
  },
  {
    name: 'UserWay',
    categories: ['accessibility'],
    website: 'https://userway.org',
    scriptSrc: ['cdn\\.userway\\.org'],
  },
  {
    name: 'Calendly',
    categories: ['misc'],
    website: 'https://calendly.com',
    scriptSrc: ['assets\\.calendly\\.com'],
    js: { Calendly: '' },
  },
  {
    name: 'Cal.com',
    categories: ['misc'],
    website: 'https://cal.com',
    scriptSrc: ['(?:app\\.)?cal\\.com/embed'],
    html: ['cal\\.com/[a-z0-9-]+'],
  },
  {
    name: 'Typeform',
    categories: ['misc'],
    website: 'https://www.typeform.com',
    scriptSrc: ['embed\\.typeform\\.com'],
    html: ['\\.typeform\\.com/to/'],
  },
  {
    name: 'Tally',
    categories: ['misc'],
    website: 'https://tally.so',
    scriptSrc: ['tally\\.so/widgets'],
    html: ['tally\\.so/r/'],
  },
  {
    name: 'Google reCAPTCHA Enterprise',
    categories: ['captcha'],
    website: 'https://cloud.google.com/recaptcha-enterprise',
    scriptSrc: ['recaptcha/enterprise\\.js'],
    implies: ['Google reCAPTCHA'],
  },
  {
    name: 'WebMCP',
    categories: ['ai'],
    website: 'https://shopify.dev',
    scriptSrc: ['webmcp-[\\d.]+\\.js', 'storefront/webmcp'],
    description: 'Model Context Protocol storefront layer for agentic commerce',
  },
];
