import type { Fingerprint } from '../types.js';

/**
 * Website platforms, CMSes, ecommerce platforms and site builders.
 *
 * These are the highest-value detections, so they get the widest signal coverage: a
 * platform that is correctly identified constrains everything else about the stack.
 */
export const platforms: Fingerprint[] = [
  {
    name: 'WordPress',
    categories: ['cms', 'platform'],
    website: 'https://wordpress.org',
    meta: { generator: { re: 'WordPress(?:\\s+([\\d.]+))?', version: '$1' } },
    html: [
      { re: '/wp-content/(?:themes|plugins|uploads)/', note: 'WordPress asset path' },
      '/wp-includes/js/',
      '<link[^>]+rel=["\']https://api\\.w\\.org/["\']',
    ],
    cookies: { '^wordpress_logged_in_': '', '^wp-settings-': '' },
    headers: { 'x-pingback': '/xmlrpc\\.php' },
    probe: [
      { path: '/wp-json/', body: '"namespace"\\s*:\\s*"wp/v2"' },
      { path: '/wp-login.php', body: 'user_login|wp-submit' },
    ],
    robots: ['Disallow:\\s*/wp-admin'],
    implies: ['PHP', 'MySQL'],
  },
  {
    name: 'Shopify',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.shopify.com',
    headers: {
      'powered-by': 'Shopify',
      'x-shopid': '',
      'x-shopify-stage': '',
      'x-sorting-hat-shopid': '',
    },
    cookies: { '^_shopify_y$': '', '^_shopify_s$': '', '^_secure_session_id$': '' },
    html: ['cdn\\.shopify\\.com', 'Shopify\\.shop\\s*=', 'shopify-section-'],
    js: { Shopify: '', 'Shopify.theme': '' },
    scriptSrc: ['cdn\\.shopify\\.com/s/', '/cdn/shopifycloud/'],
    robots: ['# we use Shopify as our ecommerce platform'],
    implies: ['Liquid', 'Ruby'],
  },
  {
    name: 'Shopify Plus',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.shopify.com/plus',
    html: ['shopify-plus', '"plan"\\s*:\\s*\\{[^}]*"shopify_plus"'],
    requires: ['Shopify'],
  },
  {
    name: 'Liquid',
    categories: ['language'],
    website: 'https://shopify.github.io/liquid/',
    description: 'Shopify template language',
  },
  {
    name: 'Wix',
    categories: ['cms', 'platform'],
    website: 'https://www.wix.com',
    meta: { generator: 'Wix\\.com Website Builder' },
    headers: { 'x-wix-request-id': '', 'x-wix-renderer-server': '' },
    html: ['static\\.parastorage\\.com', 'wixstatic\\.com'],
    scriptSrc: ['static\\.parastorage\\.com'],
  },
  {
    name: 'Squarespace',
    categories: ['cms', 'platform'],
    website: 'https://www.squarespace.com',
    html: ['static1\\.squarespace\\.com', 'Static\\.SQUARESPACE_CONTEXT', 'squarespace-cdn\\.com'],
    headers: { 'x-contextid': '' },
    js: { 'Static.SQUARESPACE_CONTEXT': '' },
  },
  {
    name: 'Webflow',
    categories: ['cms', 'platform'],
    website: 'https://webflow.com',
    meta: { generator: 'Webflow' },
    html: ['data-wf-(?:page|site|domain)', 'assets(?:-global)?\\.website-files\\.com', 'cdn\\.prod\\.website-files\\.com'],
    js: { Webflow: '' },
  },
  {
    name: 'Ghost',
    categories: ['cms'],
    website: 'https://ghost.org',
    meta: { generator: { re: 'Ghost(?:\\s+([\\d.]+))?', version: '$1' } },
    html: ['ghost-sdk', 'content_api_key|ghost\\.min\\.js', '/ghost/assets/'],
    probe: [
      {
        path: '/ghost/api/content/settings/',
        status: [200, 401, 403],
        // Ghost answers with its own error envelope. A bare 401/403 proves nothing, because
        // most sites reject unknown paths that way.
        body: '"errors"\\s*:\\s*\\[[^\\]]*(?:UnauthorizedError|ValidationError)|"settings"\\s*:',
      },
    ],
    implies: ['Node.js'],
  },
  {
    name: 'Drupal',
    categories: ['cms'],
    website: 'https://www.drupal.org',
    meta: { generator: { re: 'Drupal\\s+(\\d+)', version: '$1' } },
    headers: { 'x-drupal-cache': '', 'x-drupal-dynamic-cache': '', 'x-generator': { re: 'Drupal\\s+(\\d+)', version: '$1' } },
    html: ['/sites/(?:default|all)/(?:files|modules|themes)/', 'drupal-settings-json'],
    js: { Drupal: '' },
    implies: ['PHP'],
  },
  {
    name: 'Joomla',
    categories: ['cms'],
    website: 'https://www.joomla.org',
    meta: { generator: { re: 'Joomla!?(?:\\s*-?\\s*([\\d.]+))?', version: '$1' } },
    html: ['/media/(?:jui|system)/js/', 'option=com_'],
    implies: ['PHP'],
  },
  {
    name: 'Magento',
    categories: ['ecommerce', 'platform'],
    website: 'https://business.adobe.com/products/magento/magento-commerce.html',
    cookies: { '^X-Magento-Vary$': '', '^mage-cache-storage$': '' },
    html: ['/static/version\\d+/frontend/', 'Magento_Ui/js', 'mage/cookies'],
    js: { 'require.s.contexts._.config.paths.mage': '' },
    implies: ['PHP'],
  },
  {
    name: 'WooCommerce',
    categories: ['ecommerce', 'ecommerce-app'],
    website: 'https://woocommerce.com',
    html: [
      { re: 'woocommerce(?:-|/assets)', note: 'WooCommerce asset path' },
      'wc-ajax=',
      'class="[^"]*\\bwoocommerce\\b',
    ],
    cookies: { '^woocommerce_cart_hash$': '', '^wp_woocommerce_session_': '' },
    requires: ['WordPress'],
    implies: ['WordPress'],
  },
  {
    name: 'BigCommerce',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.bigcommerce.com',
    html: ['cdn\\d*\\.bigcommerce\\.com', 'bigcommerce\\.com/s-'],
    headers: { 'x-bc-request-id': '' },
    cookies: { '^SHOP_SESSION_TOKEN$': '' },
  },
  {
    name: 'PrestaShop',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.prestashop.com',
    meta: { generator: 'PrestaShop' },
    cookies: { '^PrestaShop-': '' },
    js: { prestashop: '' },
    implies: ['PHP'],
  },
  {
    name: 'Shopware',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.shopware.com',
    html: ['/bundles/storefront/', 'shopware'],
    headers: { 'sw-invalidation-states': '' },
    implies: ['PHP', 'Symfony'],
  },
  {
    name: 'Salesforce Commerce Cloud',
    categories: ['ecommerce', 'platform'],
    website: 'https://www.salesforce.com/products/commerce-cloud/',
    html: ['demandware\\.static', 'demandware\\.edgesuite\\.net'],
    url: ['/on/demandware\\.store/'],
    cookies: { '^dwsid$': '' },
  },
  {
    name: 'Adobe Experience Manager',
    categories: ['cms'],
    website: 'https://business.adobe.com/products/experience-manager/adobe-experience-manager.html',
    html: ['/etc\\.clientlibs/', '/content/dam/', 'cq-?dialog'],
    implies: ['Java'],
  },
  {
    name: 'Sitecore',
    categories: ['cms'],
    website: 'https://www.sitecore.com',
    cookies: { '^SC_ANALYTICS_GLOBAL_COOKIE$': '' },
    html: ['/-/media/', 'sitecore'],
    implies: ['ASP.NET'],
  },
  {
    name: 'Contentful',
    categories: ['cms'],
    website: 'https://www.contentful.com',
    requestHost: ['cdn\\.contentful\\.com', 'images\\.ctfassets\\.net', 'preview\\.contentful\\.com'],
    html: ['images\\.ctfassets\\.net', 'videos\\.ctfassets\\.net'],
    npmDep: ['^contentful$', '^@contentful/'],
  },
  {
    name: 'Sanity',
    categories: ['cms'],
    website: 'https://www.sanity.io',
    requestHost: ['cdn\\.sanity\\.io', 'apicdn\\.sanity\\.io'],
    html: ['cdn\\.sanity\\.io'],
    npmDep: ['^@sanity/', '^next-sanity$'],
  },
  {
    name: 'Strapi',
    categories: ['cms', 'backend-framework'],
    website: 'https://strapi.io',
    headers: { 'x-powered-by': 'Strapi' },
    implies: ['Node.js'],
  },
  {
    name: 'Directus',
    categories: ['cms', 'baas'],
    website: 'https://directus.io',
    headers: { 'x-powered-by': 'Directus' },
    implies: ['Node.js'],
  },
  {
    name: 'Payload CMS',
    categories: ['cms'],
    website: 'https://payloadcms.com',
    npmDep: ['^payload$', '^@payloadcms/'],
    probe: [{ path: '/api/access', status: [200, 401, 403], body: '"canAccessAdmin"|"collections"\\s*:' }],
    implies: ['Node.js'],
  },
  {
    name: 'Storyblok',
    categories: ['cms'],
    website: 'https://www.storyblok.com',
    requestHost: ['api\\.storyblok\\.com', 'a\\.storyblok\\.com'],
    html: ['a\\.storyblok\\.com'],
    npmDep: ['^@storyblok/', '^storyblok'],
  },
  {
    name: 'Prismic',
    categories: ['cms'],
    website: 'https://prismic.io',
    requestHost: ['\\.prismic\\.io', 'images\\.prismic\\.io'],
    npmDep: ['^@prismicio/'],
  },
  {
    name: 'Framer',
    categories: ['cms', 'platform'],
    website: 'https://www.framer.com',
    meta: { generator: 'Framer' },
    html: ['framerusercontent\\.com', 'framer\\.com/m/'],
  },
  {
    name: 'Bubble',
    categories: ['platform'],
    website: 'https://bubble.io',
    html: ['bubble\\.io', 'd1muf25xaso8hp\\.cloudfront\\.net'],
    meta: { generator: 'Bubble' },
  },
  {
    name: 'Craft CMS',
    categories: ['cms'],
    website: 'https://craftcms.com',
    headers: { 'x-powered-by': 'Craft CMS' },
    cookies: { '^CraftSessionId$': '' },
    implies: ['PHP', 'Yii'],
  },
  {
    name: 'Umbraco',
    categories: ['cms'],
    website: 'https://umbraco.com',
    headers: { 'x-umbraco-version': { re: '([\\d.]+)', version: '$1' } },
    cookies: { '^UMB_': '' },
    implies: ['ASP.NET'],
  },
  {
    name: 'TYPO3',
    categories: ['cms'],
    website: 'https://typo3.org',
    meta: { generator: 'TYPO3 CMS' },
    html: ['/typo3(?:conf|temp)/'],
    implies: ['PHP'],
  },
  {
    name: 'Statamic',
    categories: ['cms'],
    website: 'https://statamic.com',
    headers: { 'x-powered-by': 'Statamic' },
    implies: ['Laravel', 'PHP'],
  },
  {
    name: 'Blogger',
    categories: ['cms'],
    website: 'https://www.blogger.com',
    meta: { generator: 'blogger' },
    html: ['\\.blogspot\\.com', 'blogger\\.com/static'],
  },
  {
    name: 'Substack',
    categories: ['cms', 'platform'],
    website: 'https://substack.com',
    html: ['substackcdn\\.com', 'substack\\.com/api'],
  },
  {
    name: 'Medium',
    categories: ['cms', 'platform'],
    website: 'https://medium.com',
    html: ['cdn-client\\.medium\\.com', 'miro\\.medium\\.com'],
  },
  {
    name: 'Notion',
    categories: ['cms', 'platform'],
    website: 'https://www.notion.so',
    html: ['notion-static\\.com', 'www\\.notion\\.so/api'],
  },
  {
    name: 'Discourse',
    categories: ['platform'],
    website: 'https://www.discourse.org',
    meta: { generator: 'Discourse' },
    html: ['discourse-cdn\\.com', 'discourse_theme_id'],
    implies: ['Ruby on Rails'],
  },
  {
    name: 'Kajabi',
    categories: ['platform'],
    website: 'https://kajabi.com',
    html: ['kajabi-storefronts', 'kajabi\\.com'],
  },
  {
    name: 'Teachable',
    categories: ['platform'],
    website: 'https://teachable.com',
    html: ['teachablecdn\\.com', 'assets\\.teachablecdn\\.com'],
  },
  {
    name: 'Thinkific',
    categories: ['platform'],
    website: 'https://www.thinkific.com',
    html: ['thinkific\\.com', 'import\\.cdn\\.thinkific\\.com'],
  },
  {
    name: 'Gumroad',
    categories: ['ecommerce', 'platform'],
    website: 'https://gumroad.com',
    html: ['gumroad\\.com/js', 'assets\\.gumroad\\.com'],
  },
  {
    name: 'Circle',
    categories: ['platform'],
    website: 'https://circle.so',
    html: ['circle\\.so', 'cdn\\.circle\\.so'],
  },
  {
    name: 'HubSpot CMS',
    categories: ['cms'],
    website: 'https://www.hubspot.com/products/cms',
    html: ['cdn\\d*\\.hubspot\\.net', 'hs-sites\\.com'],
    headers: { 'x-hs-cache-config': '' },
  },
  {
    name: 'Duda',
    categories: ['cms', 'platform'],
    website: 'https://www.duda.co',
    html: ['dudaone', 'cdn\\d*\\.editmysite\\.com', 'irp-cdn\\.multiscreensite\\.com'],
  },
  {
    name: 'Odoo',
    categories: ['cms', 'ecommerce'],
    website: 'https://www.odoo.com',
    meta: { generator: { re: 'Odoo(?:\\s+([\\d.]+))?', version: '$1' } },
    html: ['/web/static/', 'odoo\\.define'],
    implies: ['Python'],
  },
  {
    name: 'Docusaurus',
    categories: ['static-site-generator', 'documentation'],
    website: 'https://docusaurus.io',
    meta: { generator: { re: 'Docusaurus(?:\\s+v?([\\d.]+))?', version: '$1' } },
    html: ['docusaurus\\.config', '__docusaurus'],
    implies: ['React'],
  },
  {
    name: 'Mintlify',
    categories: ['documentation'],
    website: 'https://mintlify.com',
    html: ['mintcdn\\.com', '_mintlify/|mintlify-assets'],
    headers: { 'x-mintlify-': '' },
  },
  {
    name: 'GitBook',
    categories: ['documentation'],
    website: 'https://www.gitbook.com',
    html: ['gitbook-cdn|files\\.gitbook\\.com', '__GITBOOK'],
    headers: { 'x-gitbook-': '' },
  },
  {
    name: 'ReadMe',
    categories: ['documentation'],
    website: 'https://readme.com',
    html: ['readme\\.io', 'readmessl\\.com'],
  },
  {
    name: 'VitePress',
    categories: ['static-site-generator', 'documentation'],
    website: 'https://vitepress.dev',
    html: ['VPHero|VPNav|vp-doc', '__VP_HASH_MAP__'],
    implies: ['Vue.js', 'Vite'],
  },
  {
    name: 'MkDocs',
    categories: ['static-site-generator', 'documentation'],
    website: 'https://www.mkdocs.org',
    meta: { generator: { re: 'mkdocs-?([\\d.]+)?', version: '$1' } },
    html: ['/assets/javascripts/bundle', 'md-container|md-nav'],
    implies: ['Python'],
  },
  {
    name: 'Sphinx',
    categories: ['static-site-generator', 'documentation'],
    website: 'https://www.sphinx-doc.org',
    meta: { generator: { re: 'Docutils|Sphinx\\s*([\\d.]+)?', version: '$1' } },
    html: ['_static/documentation_options\\.js', 'sphinxsidebar'],
    implies: ['Python'],
  },
  {
    name: 'Zendesk Guide',
    categories: ['documentation', 'support'],
    website: 'https://www.zendesk.com/service/help-center/',
    html: ['zdassets\\.com/hc/', 'zendesk\\.com/hc/'],
  },
];
