import type { Fingerprint } from '../types.js';

/** Authentication and identity providers. */
export const auth: Fingerprint[] = [
  {
    name: 'Auth0',
    categories: ['auth'],
    website: 'https://auth0.com',
    scriptSrc: ['cdn\\.auth0\\.com'],
    requestHost: ['\\.auth0\\.com'],
    npmDep: ['^@auth0/', '^auth0-'],
  },
  {
    name: 'Clerk',
    categories: ['auth'],
    website: 'https://clerk.com',
    scriptSrc: ['clerk\\.(?:com|dev|accounts\\.dev)', '\\.clerk\\.accounts\\.dev'],
    requestHost: ['clerk\\.[a-z0-9-]+\\.(?:com|dev)', '\\.clerk\\.accounts\\.dev'],
    js: { Clerk: '' },
    npmDep: ['^@clerk/'],
  },
  {
    name: 'WorkOS',
    categories: ['auth'],
    website: 'https://workos.com',
    requestHost: ['api\\.workos\\.com', '\\.authkit\\.app'],
    npmDep: ['^@workos-inc/'],
  },
  {
    name: 'Okta',
    categories: ['auth'],
    website: 'https://www.okta.com',
    requestHost: ['\\.okta(?:preview|-emea)?\\.com'],
    npmDep: ['^@okta/'],
  },
  {
    name: 'Firebase Authentication',
    categories: ['auth'],
    website: 'https://firebase.google.com/products/auth',
    requestHost: ['identitytoolkit\\.googleapis\\.com', 'securetoken\\.googleapis\\.com'],
    implies: ['Firebase'],
  },
  {
    name: 'Amazon Cognito',
    categories: ['auth'],
    website: 'https://aws.amazon.com/cognito/',
    requestHost: ['cognito-(?:idp|identity)\\.[a-z0-9-]+\\.amazonaws\\.com'],
    implies: ['Amazon Web Services'],
  },
  {
    name: 'NextAuth.js',
    categories: ['auth'],
    website: 'https://next-auth.js.org',
    cookies: { '^(?:__Secure-)?next-auth\\.session-token$': '', '^next-auth\\.csrf-token$': '' },
    npmDep: ['^next-auth$'],
  },
  {
    name: 'Auth.js',
    categories: ['auth'],
    website: 'https://authjs.dev',
    cookies: { '^(?:__Secure-)?authjs\\.session-token$': '' },
    npmDep: ['^@auth/'],
  },
  {
    name: 'Better Auth',
    categories: ['auth'],
    website: 'https://www.better-auth.com',
    cookies: { '^(?:__Secure-)?better-auth\\.session_token$': '' },
    npmDep: ['^better-auth$'],
  },
  {
    name: 'Keycloak',
    categories: ['auth'],
    website: 'https://www.keycloak.org',
    html: ['/auth/realms/', '/realms/[^/]+/protocol/openid-connect'],
    cookies: { '^KEYCLOAK_': '', '^AUTH_SESSION_ID$': '' },
    implies: ['Java'],
  },
  {
    name: 'Stytch',
    categories: ['auth'],
    website: 'https://stytch.com',
    requestHost: ['\\.stytch\\.com'],
    npmDep: ['^@stytch/'],
  },
  {
    name: 'SuperTokens',
    categories: ['auth'],
    website: 'https://supertokens.com',
    cookies: { '^sAccessToken$': '', '^sFrontToken$': '' },
    npmDep: ['^supertokens-'],
  },
  {
    name: 'Kinde',
    categories: ['auth'],
    website: 'https://kinde.com',
    requestHost: ['\\.kinde\\.com'],
    npmDep: ['^@kinde-oss/'],
  },
  {
    name: 'Descope',
    categories: ['auth'],
    website: 'https://www.descope.com',
    requestHost: ['api\\.descope\\.com'],
    npmDep: ['^@descope/'],
  },
];

/** Backend-as-a-service platforms and databases reachable from the client. */
export const data: Fingerprint[] = [
  {
    name: 'Supabase',
    categories: ['baas', 'database'],
    website: 'https://supabase.com',
    requestHost: ['[a-z0-9]{15,}\\.supabase\\.(?:co|in)'],
    html: [{ re: '[a-z0-9]{15,}\\.supabase\\.co', confidence: 0.6 }],
    npmDep: ['^@supabase/'],
    implies: ['PostgreSQL'],
  },
  {
    name: 'Firebase',
    categories: ['baas'],
    website: 'https://firebase.google.com',
    requestHost: ['firebaseio\\.com', 'firestore\\.googleapis\\.com', 'firebaseapp\\.com'],
    npmDep: ['^firebase$', '^@firebase/'],
    implies: ['Google Cloud'],
  },
  {
    name: 'Appwrite',
    categories: ['baas'],
    website: 'https://appwrite.io',
    requestHost: ['\\.appwrite\\.(?:io|global)'],
    npmDep: ['^appwrite$'],
  },
  {
    name: 'PocketBase',
    categories: ['baas'],
    website: 'https://pocketbase.io',
    probe: [{ path: '/api/health', body: '"code"\\s*:\\s*200' }],
    npmDep: ['^pocketbase$'],
  },
  {
    name: 'Convex',
    categories: ['baas', 'database'],
    website: 'https://www.convex.dev',
    requestHost: ['\\.convex\\.cloud'],
    npmDep: ['^convex$'],
  },
  {
    name: 'Hasura',
    categories: ['baas'],
    website: 'https://hasura.io',
    requestHost: ['\\.hasura\\.app'],
    headers: { 'x-hasura-': '' },
  },
  {
    name: 'PlanetScale',
    categories: ['database'],
    website: 'https://planetscale.com',
    npmDep: ['^@planetscale/'],
    implies: ['MySQL'],
  },
  {
    name: 'Neon',
    categories: ['database'],
    website: 'https://neon.tech',
    npmDep: ['^@neondatabase/'],
    implies: ['PostgreSQL'],
  },
  {
    name: 'Turso',
    categories: ['database'],
    website: 'https://turso.tech',
    npmDep: ['^@libsql/'],
    implies: ['SQLite'],
  },
  { name: 'SQLite', categories: ['database'], website: 'https://www.sqlite.org' },
  {
    name: 'Upstash',
    categories: ['database'],
    website: 'https://upstash.com',
    requestHost: ['\\.upstash\\.io'],
    npmDep: ['^@upstash/'],
  },
  {
    name: 'Prisma',
    categories: ['database'],
    website: 'https://www.prisma.io',
    npmDep: ['^@prisma/', '^prisma$'],
  },
  {
    name: 'Drizzle ORM',
    categories: ['database'],
    website: 'https://orm.drizzle.team',
    npmDep: ['^drizzle-orm$'],
  },
];

/** Site search providers. */
export const search: Fingerprint[] = [
  {
    name: 'Algolia',
    categories: ['search'],
    website: 'https://www.algolia.com',
    requestHost: ['\\.algolia(?:net|\\.net)\\.com', '[a-z0-9]+[-.]dsn\\.algolia\\.net', '\\.algolianet\\.com'],
    scriptSrc: ['cdn\\.jsdelivr\\.net/npm/(?:algoliasearch|instantsearch)'],
    npmDep: ['^algoliasearch$', '^instantsearch', '^react-instantsearch'],
    js: { algoliasearch: '', instantsearch: '' },
  },
  {
    name: 'Typesense',
    categories: ['search'],
    website: 'https://typesense.org',
    requestHost: ['\\.typesense\\.net'],
    npmDep: ['^typesense$'],
  },
  {
    name: 'Meilisearch',
    categories: ['search'],
    website: 'https://www.meilisearch.com',
    requestHost: ['\\.meilisearch\\.(?:com|io)'],
    npmDep: ['^meilisearch$'],
  },
  {
    name: 'Elasticsearch',
    categories: ['search'],
    website: 'https://www.elastic.co/elasticsearch',
    headers: { 'x-elastic-product': 'Elasticsearch' },
    probe: [{ path: '/_cluster/health', body: '"cluster_name"' }],
  },
  {
    name: 'Coveo',
    categories: ['search'],
    website: 'https://www.coveo.com',
    requestHost: ['\\.coveo\\.com'],
  },
  {
    name: 'Klevu',
    categories: ['search'],
    website: 'https://www.klevu.com',
    scriptSrc: ['js\\.klevu\\.com', 'klevu\\.com'],
  },
  {
    name: 'Doofinder',
    categories: ['search'],
    website: 'https://www.doofinder.com',
    scriptSrc: ['cdn\\.doofinder\\.com'],
  },
  {
    name: 'Orama',
    categories: ['search'],
    website: 'https://orama.com',
    npmDep: ['^@orama/'],
  },
  {
    name: 'Pagefind',
    categories: ['search'],
    website: 'https://pagefind.app',
    html: ['/pagefind/pagefind'],
    scriptSrc: ['/pagefind/'],
  },
  {
    name: 'Lunr.js',
    categories: ['search'],
    website: 'https://lunrjs.com',
    scriptSrc: ['lunr(?:\\.min)?\\.js'],
    js: { lunr: '' },
  },
];

/** Error tracking, APM and observability. */
export const observability: Fingerprint[] = [
  {
    name: 'Sentry',
    categories: ['error-tracking', 'apm'],
    website: 'https://sentry.io',
    scriptSrc: ['browser\\.sentry-cdn\\.com', 'js\\.sentry-cdn\\.com'],
    js: { Sentry: '', __SENTRY__: '' },
    requestHost: ['\\.ingest(?:\\.[a-z]+)?\\.sentry\\.io', 'sentry\\.io'],
    npmDep: ['^@sentry/'],
  },
  {
    name: 'Bugsnag',
    categories: ['error-tracking'],
    website: 'https://www.bugsnag.com',
    scriptSrc: ['d2wy8f7a9ursnm\\.cloudfront\\.net', 'bugsnag'],
    js: { Bugsnag: '' },
    npmDep: ['^@bugsnag/'],
  },
  {
    name: 'Rollbar',
    categories: ['error-tracking'],
    website: 'https://rollbar.com',
    scriptSrc: ['cdn\\.rollbar\\.com'],
    js: { Rollbar: '' },
  },
  {
    name: 'Datadog',
    categories: ['apm'],
    website: 'https://www.datadoghq.com',
    scriptSrc: ['datadoghq-browser-agent\\.com', 'datadog'],
    js: { DD_RUM: '', DD_LOGS: '' },
    npmDep: ['^@datadog/'],
  },
  {
    name: 'New Relic',
    categories: ['apm'],
    website: 'https://newrelic.com',
    scriptSrc: ['js-agent\\.newrelic\\.com'],
    js: { NREUM: '', newrelic: '' },
  },
  {
    name: 'Dynatrace',
    categories: ['apm'],
    website: 'https://www.dynatrace.com',
    scriptSrc: ['ruxitagentjs', 'dynatrace'],
    js: { dT_: '', dynatrace: '' },
  },
  {
    name: 'Grafana Faro',
    categories: ['apm'],
    website: 'https://grafana.com/oss/faro/',
    npmDep: ['^@grafana/faro-'],
  },
  {
    name: 'OpenTelemetry',
    categories: ['apm'],
    website: 'https://opentelemetry.io',
    npmDep: ['^@opentelemetry/'],
    headers: { traceparent: '' },
  },
  {
    name: 'Honeybadger',
    categories: ['error-tracking'],
    website: 'https://www.honeybadger.io',
    scriptSrc: ['js\\.honeybadger\\.io'],
    js: { Honeybadger: '' },
  },
  {
    name: 'Raygun',
    categories: ['error-tracking'],
    website: 'https://raygun.com',
    scriptSrc: ['cdn\\.raygun\\.io'],
    js: { rg4js: '' },
  },
];

/** Customer support, live chat and CRM. */
export const support: Fingerprint[] = [
  {
    name: 'Intercom',
    categories: ['support', 'chat'],
    website: 'https://www.intercom.com',
    scriptSrc: ['widget\\.intercom\\.io', 'js\\.intercomcdn\\.com'],
    js: { Intercom: '', intercomSettings: '' },
  },
  {
    name: 'Zendesk',
    categories: ['support', 'chat'],
    website: 'https://www.zendesk.com',
    scriptSrc: ['static\\.zdassets\\.com', 'ekr\\.zdassets\\.com'],
    js: { zE: '', zESettings: '' },
  },
  {
    name: 'Crisp',
    categories: ['support', 'chat'],
    website: 'https://crisp.chat',
    scriptSrc: ['client\\.crisp\\.chat'],
    js: { $crisp: '', CRISP_WEBSITE_ID: '' },
  },
  {
    name: 'Tawk.to',
    categories: ['support', 'chat'],
    website: 'https://www.tawk.to',
    scriptSrc: ['embed\\.tawk\\.to'],
    js: { Tawk_API: '' },
  },
  {
    name: 'Drift',
    categories: ['support', 'chat'],
    website: 'https://www.drift.com',
    scriptSrc: ['js\\.driftt\\.com', 'js\\.drift\\.com'],
    js: { drift: '' },
  },
  {
    name: 'LiveChat',
    categories: ['support', 'chat'],
    website: 'https://www.livechat.com',
    scriptSrc: ['cdn\\.livechatinc\\.com'],
    js: { LC_API: '', __lc: '' },
  },
  {
    name: 'Freshchat',
    categories: ['support', 'chat'],
    website: 'https://www.freshworks.com/live-chat-software/',
    scriptSrc: ['wchat\\.freshchat\\.com', 'wchat\\.(?:eu|in)\\.freshchat\\.com'],
    js: { fcWidget: '' },
  },
  {
    name: 'Tidio',
    categories: ['support', 'chat'],
    website: 'https://www.tidio.com',
    scriptSrc: ['code\\.tidio\\.co'],
    js: { tidioChatApi: '' },
  },
  {
    name: 'Help Scout',
    categories: ['support'],
    website: 'https://www.helpscout.com',
    scriptSrc: ['beacon-v2\\.helpscout\\.net'],
    js: { Beacon: '' },
  },
  {
    name: 'Chatwoot',
    categories: ['support', 'chat'],
    website: 'https://www.chatwoot.com',
    scriptSrc: ['/packs/js/sdk\\.js', 'chatwoot'],
    js: { chatwootSDK: '' },
  },
  {
    name: 'HubSpot',
    categories: ['crm', 'marketing-automation'],
    website: 'https://www.hubspot.com',
    scriptSrc: ['js\\.hs-scripts\\.com', 'js\\.hsforms\\.net', 'js\\.hsadspixel\\.net'],
    js: { _hsq: '', HubSpotConversations: '' },
  },
];

/** Email, SMS and marketing automation. */
export const marketing: Fingerprint[] = [
  {
    name: 'Klaviyo',
    categories: ['email', 'marketing-automation'],
    website: 'https://www.klaviyo.com',
    scriptSrc: [{ re: 'static\\.klaviyo\\.com/onsite/js/([A-Za-z0-9]{6})/', id: '$1' }, 'static(?:-tracking)?\\.klaviyo\\.com'],
    js: { klaviyo: '', _learnq: '' },
    requestHost: ['\\.klaviyo\\.com'],
  },
  {
    name: 'Mailchimp',
    categories: ['email', 'marketing-automation'],
    website: 'https://mailchimp.com',
    scriptSrc: ['chimpstatic\\.com', 'downloads\\.mailchimp\\.com'],
    html: ['list-manage\\.com/subscribe'],
  },
  {
    name: 'ActiveCampaign',
    categories: ['email', 'marketing-automation'],
    website: 'https://www.activecampaign.com',
    scriptSrc: ['prism\\.app-us1\\.com', 'activehosted\\.com'],
    js: { vgo: '' },
  },
  {
    name: 'Marketo',
    categories: ['marketing-automation'],
    website: 'https://business.adobe.com/products/marketo/adobe-marketo.html',
    scriptSrc: ['munchkin\\.js', 'munchkin\\.marketo\\.net'],
    js: { Munchkin: '' },
  },
  {
    name: 'Pardot',
    categories: ['marketing-automation'],
    website: 'https://www.salesforce.com/products/marketing-cloud/account-engagement/',
    scriptSrc: ['pi\\.pardot\\.com'],
    js: { piAId: '' },
  },
  {
    name: 'Braze',
    categories: ['marketing-automation'],
    website: 'https://www.braze.com',
    npmDep: ['^@braze/'],
    js: { appboy: '', braze: '' },
  },
  {
    name: 'Customer.io',
    categories: ['marketing-automation'],
    website: 'https://customer.io',
    scriptSrc: ['assets\\.customer\\.io', 'cdp\\.customer\\.io'],
    js: { _cio: '' },
  },
  {
    name: 'OneSignal',
    categories: ['marketing-automation'],
    website: 'https://onesignal.com',
    scriptSrc: ['cdn\\.onesignal\\.com'],
    js: { OneSignal: '' },
  },
  {
    name: 'Brevo',
    categories: ['email', 'marketing-automation'],
    website: 'https://www.brevo.com',
    scriptSrc: ['sibautomation\\.com', 'sendinblue\\.com'],
    js: { sib: '' },
  },
  {
    name: 'ConvertKit',
    categories: ['email'],
    website: 'https://kit.com',
    scriptSrc: ['f\\.convertkit\\.com', 'ck\\.page'],
  },
  {
    name: 'Attentive',
    categories: ['marketing-automation'],
    website: 'https://www.attentive.com',
    scriptSrc: ['cdn\\.attn\\.tv'],
  },
  {
    name: 'Postscript',
    categories: ['marketing-automation'],
    website: 'https://postscript.io',
    scriptSrc: ['sdk\\.postscript\\.io'],
  },
  {
    name: 'Omnisend',
    categories: ['email', 'marketing-automation'],
    website: 'https://www.omnisend.com',
    scriptSrc: ['omnisnippet\\d?\\.com'],
    js: { omnisend: '' },
  },
];

/** CAPTCHA, bot management and fraud prevention. */
export const security: Fingerprint[] = [
  {
    name: 'Google reCAPTCHA',
    categories: ['captcha'],
    website: 'https://developers.google.com/recaptcha',
    scriptSrc: ['(?:www\\.google\\.com|www\\.gstatic\\.com|recaptcha\\.net)/recaptcha'],
    html: ['g-recaptcha', 'grecaptcha'],
    js: { grecaptcha: '' },
  },
  {
    name: 'hCaptcha',
    categories: ['captcha'],
    website: 'https://www.hcaptcha.com',
    scriptSrc: ['(?:js|newassets)\\.hcaptcha\\.com'],
    js: { hcaptcha: '' },
  },
  {
    name: 'Cloudflare Turnstile',
    categories: ['captcha'],
    website: 'https://www.cloudflare.com/products/turnstile/',
    scriptSrc: ['challenges\\.cloudflare\\.com/turnstile'],
    js: { turnstile: '' },
    implies: ['Cloudflare'],
  },
  {
    name: 'DataDome',
    categories: ['bot-protection'],
    website: 'https://datadome.co',
    scriptSrc: ['js\\.datadome\\.co'],
    cookies: { '^datadome$': '' },
  },
  {
    name: 'PerimeterX',
    categories: ['bot-protection'],
    website: 'https://www.humansecurity.com',
    scriptSrc: ['client\\.perimeterx\\.net', 'px-cdn\\.net'],
    cookies: { '^_px': '' },
  },
  {
    name: 'Kasada',
    categories: ['bot-protection'],
    website: 'https://www.kasada.io',
    html: ['/149e9513-01fa-4fb0-aad4-566afd725d1b/'],
    headers: { 'x-kpsdk-ct': '' },
  },
  {
    name: 'FingerprintJS',
    categories: ['bot-protection'],
    website: 'https://fingerprint.com',
    scriptSrc: ['fpjs\\.(?:io|dev)', 'openfpcdn\\.io', 'fingerprintjs'],
    requestHost: ['\\.fpjs\\.io', '\\.openfpcdn\\.io'],
    npmDep: ['^@fingerprintjs/'],
  },
  {
    name: 'Arkose Labs',
    categories: ['captcha', 'bot-protection'],
    website: 'https://www.arkoselabs.com',
    scriptSrc: ['client-api\\.arkoselabs\\.com', 'funcaptcha\\.com'],
  },
];
